export { createLoroBridge } from "./loro-bridge.js";
export type { LoroBridge, LoroChangeHandler } from "./loro-bridge.js";
export { createCrdtStore } from "./stores/use-crdt-store.js";
export type { CrdtStore, CrdtStoreState, CrdtStoreActions } from "./stores/use-crdt-store.js";
export { executeLua, createLuaEngine } from "./lua/lua-runtime.js";

// ── Object Model ───────────────────────────────────────────────────────────────
export {
  objectId,
  edgeId,
  ObjectRegistry,
  TreeModel,
  TreeModelError,
  EdgeModel,
  WeakRefEngine,
  NSIDRegistry,
  isValidNSID,
  parseNSID,
  nsid,
  nsidAuthority,
  nsidName,
  isValidPrismAddress,
  prismAddress,
  parsePrismAddress,
  queryToParams,
  paramsToQuery,
  matchesQuery,
  sortObjects,
} from "./object-model/index.js";

export type {
  ObjectId,
  EdgeId,
  EntityFieldType,
  EntityFieldDef,
  GraphObject,
  ObjectEdge,
  ResolvedEdge,
  EdgeBehavior,
  EdgeTypeDef,
  EntityDef,
  CategoryRule,
  TabDefinition,
  SlotDef,
  SlotRegistration,
  TreeNode,
  WeakRefChildNode,
  TreeModelEvent,
  TreeModelEventListener,
  TreeModelHooks,
  TreeModelErrorCode,
  TreeModelOptions,
  AddOptions,
  DuplicateOptions,
  EdgeModelEvent,
  EdgeModelEventListener,
  EdgeModelHooks,
  EdgeModelOptions,
  WeakRefExtraction,
  WeakRefProvider,
  WeakRefChild,
  WeakRefEngineEvent,
  WeakRefEngineEventListener,
  WeakRefEngineOptions,
  NSID,
  PrismAddress,
  ObjectQuery,
} from "./object-model/index.js";
