//! # prism-ui-build
//!
//! Compile-time codegen for `.prui` files. Each consumer crate
//! calls `prism_ui_build::compile("ui/app.prui")` from its
//! `build.rs`; the generated Rust module is emitted into `OUT_DIR`
//! and brought into scope via `include!(concat!(env!("OUT_DIR"),
//! "/<file>.rs"))`.
//!
//! See ADR-008 and `docs/dev/clay-migration-plan.md` §4.6.
//!
//! Phase 2 wiring: parses the source through
//! `prism_core::language::prism_ui::parse`, validates it at build
//! time, then emits a thin Rust module that exposes
//!
//! - `SOURCE`: the original `.prui` text for the runtime
//!   interpret path,
//! - `COMPONENT_NAMES`: every `<component name="...">` in document
//!   order,
//! - `nodes()`: a runtime helper that re-parses `SOURCE` through
//!   `prism_ui_runtime::interpret::interpret` and returns a
//!   `Vec<prism_ui_runtime::layout::Node>` ready for `Surface::new`.
//!
//! Re-parsing at runtime keeps the source canonical (per plan §4.6 —
//! `.prui` is the source of truth, the AST is derived) and lets
//! live edits use the same path. Build-time validation guarantees
//! `nodes()` cannot panic on a parse error in shipped binaries.

use std::path::Path;

use prism_core::language::prism_ui::{parse, AttributeValue, Document, Element, Node, ParseError};

pub mod prss_hash;
pub mod prss_watch;
pub mod prui_doc;
pub mod template_hash;
pub mod template_watch;
pub use prss_hash::{
    collect_prss_literal_slots, compare_prss_fingerprints, prss_full_hash, prss_structural_hash,
    PrssFingerprint, PrssLiteralOwner, PrssLiteralPatch, PrssLiteralSlot, PrssPatchOutcome,
    PrssTokenBucket,
};
pub use prss_watch::{PrssChange, PrssFingerprintCache};
pub use prui_doc::{PruiDocCache, PruiDocChange, StyleDelta};
pub use template_hash::{
    collect_literal_slots, compare_fingerprints, full_hash, structural_hash, LiteralPatch,
    LiteralSlot, PatchOutcome, TemplateFingerprint,
};
pub use template_watch::{FingerprintCache, TemplateChange};

#[derive(Debug, thiserror::Error)]
pub enum CompileError {
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("{count} parse error(s): {first}")]
    Parse { count: usize, first: String },
}

/// Parse a `.prui` file from disk and emit the generated Rust
/// module.
pub fn compile(path: impl AsRef<Path>) -> Result<String, CompileError> {
    let source = std::fs::read_to_string(path.as_ref())?;
    compile_source(&source)
}

/// Parse a `.prui` source string and emit the generated Rust
/// module. Errors from the grammar bubble up as [`CompileError::Parse`]
/// — recoverable diagnostics still abort the build, since
/// `prism-ui-build` is a build-script entry point.
pub fn compile_source(source: &str) -> Result<String, CompileError> {
    let (document, errors) = parse(source);
    if !errors.is_empty() {
        return Err(CompileError::Parse {
            count: errors.len(),
            first: format_error(&errors[0]),
        });
    }
    Ok(emit_module(source, &document))
}

fn format_error(err: &ParseError) -> String {
    format!(
        "{} at {}:{}",
        err.message, err.range.start.line, err.range.start.column
    )
}

fn emit_module(source: &str, document: &Document) -> String {
    let component_names = collect_component_names(document);
    let escaped_source = escape_rust_string(source);
    let structural = template_hash::structural_hash(document);
    let full = template_hash::full_hash(document);

    let mut out = String::new();
    out.push_str("// @generated by prism-ui-build — do not edit by hand.\n");
    out.push_str("// Regenerate by re-running the consumer crate's build script.\n\n");

    out.push_str("/// Original `.prui` source the runtime interpret path\n");
    out.push_str("/// consumes for live editing.\n");
    out.push_str("pub const SOURCE: &str = \"");
    out.push_str(&escaped_source);
    out.push_str("\";\n\n");

    // Phase 10 of `docs/dev/dioxus-inspiration.md`: structural +
    // full hash for hot-reload fast-pathing. Runtime compares the
    // new template's structural hash to STRUCTURAL_HASH; equal
    // means only literals changed and the patch skips AST
    // re-evaluation.
    out.push_str("/// Structural fingerprint of [`SOURCE`] — same\n");
    out.push_str("/// tree shape → same hash. Phase 10 of\n");
    out.push_str("/// `docs/dev/dioxus-inspiration.md`.\n");
    out.push_str(&format!(
        "pub const STRUCTURAL_HASH: u64 = {structural};\n\n"
    ));
    out.push_str("/// Full fingerprint of [`SOURCE`] — every literal\n");
    out.push_str("/// value included. Pairs with `STRUCTURAL_HASH` for\n");
    out.push_str("/// the hot-reload fast path.\n");
    out.push_str(&format!("pub const FULL_HASH: u64 = {full};\n\n"));

    out.push_str("/// Names of every `<component>` declaration found in\n");
    out.push_str("/// [`SOURCE`], in document order.\n");
    out.push_str("pub const COMPONENT_NAMES: &[&str] = &[\n");
    for name in &component_names {
        out.push_str("    \"");
        out.push_str(&escape_rust_string(name));
        out.push_str("\",\n");
    }
    out.push_str("];\n\n");

    out.push_str("/// Runtime helper — re-parses [`SOURCE`] through\n");
    out.push_str("/// `prism_ui_runtime::interpret::interpret` and returns the\n");
    out.push_str("/// lowered layout-node tree. Build-time validation guarantees\n");
    out.push_str("/// the parse succeeds; an `expect` here is the assertion that\n");
    out.push_str("/// the shipped binary's source matches the one the build saw.\n");
    out.push_str("pub fn nodes() -> Vec<prism_ui_runtime::layout::Node> {\n");
    out.push_str(
        "    prism_ui_runtime::interpret::interpret(SOURCE).expect(\"prism-ui-build: SOURCE was validated at build time\")\n",
    );
    out.push_str("}\n");

    out
}

fn collect_component_names(document: &Document) -> Vec<String> {
    let mut out = Vec::new();
    for node in &document.nodes {
        walk_for_components(node, &mut out);
    }
    out
}

fn walk_for_components(node: &Node, out: &mut Vec<String>) {
    if let Node::Element(el) = node {
        if el.tag == "component" {
            if let Some(name) = attribute_string_value(el, "name") {
                out.push(name);
            }
        }
        for child in &el.children {
            walk_for_components(child, out);
        }
    }
}

fn attribute_string_value(element: &Element, name: &str) -> Option<String> {
    element
        .attributes
        .iter()
        .find(|a| a.name.raw == name)
        .and_then(|a| match &a.value {
            AttributeValue::String { value, .. } => Some(value.clone()),
            _ => None,
        })
}

fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_file_is_io_error() {
        let err = compile("/definitely/not/a/file.prui").unwrap_err();
        assert!(matches!(err, CompileError::Io(_)));
    }

    #[test]
    fn empty_source_emits_module_skeleton() {
        let out = compile_source("").unwrap();
        assert!(out.contains("@generated by prism-ui-build"));
        assert!(out.contains("pub const SOURCE: &str = \"\";"));
        assert!(out.contains("pub const COMPONENT_NAMES: &[&str] = &[\n];"));
        assert!(out.contains("pub fn nodes() -> Vec<prism_ui_runtime::layout::Node>"));
    }

    #[test]
    fn extracts_component_declarations() {
        let src = r#"<component name="Card"><heading>Hi</heading></component>
<component name="Pill"><text>x</text></component>"#;
        let out = compile_source(src).unwrap();
        assert!(out.contains("\"Card\""));
        assert!(out.contains("\"Pill\""));
    }

    #[test]
    fn preserves_source_round_trip() {
        let src = r#"<button label="Save" on:click="emit save"/>"#;
        let out = compile_source(src).unwrap();
        assert!(out.contains("Save"));
        assert!(out.contains("on:click"));
    }

    #[test]
    fn parse_errors_are_surfaced() {
        // Unclosed tag — the grammar reports a recoverable error.
        let err = compile_source("<container>").unwrap_err();
        assert!(matches!(err, CompileError::Parse { .. }));
    }

    #[test]
    fn emit_module_includes_structural_and_full_hash() {
        // Phase 10 of `docs/dev/dioxus-inspiration.md`. The
        // generated module exposes the template fingerprint as
        // compile-time consts so the hot-reload consumer can
        // compare against a runtime-reparsed template's hash.
        let out = compile_source(r#"<button label="Save"/>"#).unwrap();
        assert!(out.contains("pub const STRUCTURAL_HASH: u64 = "));
        assert!(out.contains("pub const FULL_HASH: u64 = "));
    }
}
