//! # prism-ui-build
//!
//! Compile-time codegen for `.prism-ui` files. Each consumer crate
//! calls `prism_ui_build::compile("ui/app.prism-ui")` from its
//! `build.rs`; the generated Rust module is emitted into `OUT_DIR`
//! and brought into scope via `include!(concat!(env!("OUT_DIR"),
//! "/app.rs"))` (or a thin `prism_ui::include_modules!()` macro
//! once the parser lands).
//!
//! See ADR-008 and `docs/dev/clay-migration-plan.md` §4.6.

use std::path::Path;

#[derive(Debug, thiserror::Error)]
pub enum CompileError {
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("parse error: {0}")]
    Parse(String),
}

/// Compile a `.prism-ui` source file to a Rust module string.
///
/// **Phase 0 stub.** Phase 2 wires this through
/// `prism_core::language::prism_ui::parse` → AST → emitter.
pub fn compile(path: impl AsRef<Path>) -> Result<String, CompileError> {
    let _source = std::fs::read_to_string(path.as_ref())?;
    Ok(String::from(
        "// generated by prism-ui-build (Phase 0 stub)\n\
         pub fn __prism_ui_placeholder() {}\n",
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_file_is_io_error() {
        let err = compile("/definitely/not/a/file.prism-ui").unwrap_err();
        assert!(matches!(err, CompileError::Io(_)));
    }
}
