//! Hand-maintained registry of every type in `prism-core` that has been
//! annotated with `#[luau_expose]`. The codegen subcommand
//! (`prism codegen luau-types`) walks this slice to produce the
//! consolidated `.d.luau` stub tree described in
//! `docs/dev/luau-integration-plan.md` §Phase 5.
//!
//! Why a hand list instead of `inventory!`-style link-time collection:
//! the daemon is built as `cdylib` + `staticlib` + WASM, where
//! distributed slice strategies are flaky. A plain function returning
//! `&[(&str, &str)]` works on every target and stays trivial to audit.
//! Add a new entry here whenever a new `#[luau_expose]` annotation
//! lands.

use crate::design_tokens::{Colors, DesignTokens, Radius, Rgba, Spacing, Typography};
use crate::shell_mode::{Permission, ShellMode};

/// Every Luau-exposed type defined in `prism-core`. Each entry is
/// `(luau type name, full `export type` declaration)`.
pub fn type_defs() -> &'static [(&'static str, &'static str)] {
    &[
        (DesignTokens::LUAU_TYPE_NAME, DesignTokens::LUAU_TYPE_DEF),
        (Colors::LUAU_TYPE_NAME, Colors::LUAU_TYPE_DEF),
        (Spacing::LUAU_TYPE_NAME, Spacing::LUAU_TYPE_DEF),
        (Radius::LUAU_TYPE_NAME, Radius::LUAU_TYPE_DEF),
        (Typography::LUAU_TYPE_NAME, Typography::LUAU_TYPE_DEF),
        (Rgba::LUAU_TYPE_NAME, Rgba::LUAU_TYPE_DEF),
        (ShellMode::LUAU_TYPE_NAME, ShellMode::LUAU_TYPE_DEF),
        (Permission::LUAU_TYPE_NAME, Permission::LUAU_TYPE_DEF),
    ]
}

/// Concatenate every entry from [`type_defs`] into a single Luau source
/// file, prefixed with `--!strict`. Stable ordering: matches the slice
/// order, which is curated leaf-first so dependent types declare after
/// their dependencies. Luau's type checker is order-insensitive within
/// a file, but readers aren't.
pub fn render_type_stubs() -> String {
    let mut out = String::from("--!strict\n-- Generated by `prism codegen luau-types`. Do not edit by hand.\n\n");
    for (_, def) in type_defs() {
        out.push_str(def);
        out.push_str("\n\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_design_token_type_is_registered() {
        let names: Vec<&str> = type_defs().iter().map(|(n, _)| *n).collect();
        for expected in [
            "DesignTokens",
            "Colors",
            "Spacing",
            "Radius",
            "Typography",
            "Rgba",
        ] {
            assert!(
                names.contains(&expected),
                "missing {expected} from luau type registry"
            );
        }
    }

    #[test]
    fn rgba_def_describes_four_u8_fields_as_numbers() {
        assert_eq!(
            Rgba::LUAU_TYPE_DEF,
            "export type Rgba = {\n    r: number,\n    g: number,\n    b: number,\n    a: number,\n}"
        );
    }

    #[test]
    fn design_tokens_def_references_nested_types_by_name() {
        let def = DesignTokens::LUAU_TYPE_DEF;
        assert!(def.contains("colors: Colors"));
        assert!(def.contains("spacing: Spacing"));
        assert!(def.contains("radius: Radius"));
        assert!(def.contains("typography: Typography"));
    }

    #[test]
    fn shell_mode_def_is_string_union() {
        assert_eq!(
            ShellMode::LUAU_TYPE_DEF,
            "export type ShellMode = \"Use\" | \"Build\" | \"Admin\""
        );
    }

    #[test]
    fn render_type_stubs_emits_strict_header_and_every_def() {
        let rendered = render_type_stubs();
        assert!(rendered.starts_with("--!strict\n"));
        for (_, def) in type_defs() {
            assert!(rendered.contains(def), "stub missing: {def}");
        }
    }
}
