//! Hand-maintained registry of every type in `prism-core` that has been
//! annotated with `#[luau_expose]` or hand-rolled in
//! [`crate::luau_bindings`]. The codegen subcommand (`prism codegen
//! luau-types`) walks this slice to produce the consolidated `.d.luau`
//! stub tree described in `docs/dev/luau-integration-plan.md` §Phase 5.
//!
//! Why a hand list instead of `inventory!`-style link-time collection:
//! the daemon is built as `cdylib` + `staticlib` + WASM, where
//! distributed slice strategies are flaky. A plain function returning
//! `&[(&str, &str)]` works on every target and stays trivial to audit.
//! Add a new entry here whenever a new annotation lands.

/// Collapse a list of `#[luau_expose]`-annotated types into the
/// `(LUAU_TYPE_NAME, LUAU_TYPE_DEF)` pairs the registry walks. Replaces
/// the per-type pair literal that the registry table used to spell out
/// by hand.
#[macro_export]
macro_rules! luau_types {
    ($($t:ty),* $(,)?) => {
        ::std::vec![
            $((<$t>::LUAU_TYPE_NAME, <$t>::LUAU_TYPE_DEF),)*
        ]
    };
}

use crate::design_tokens::{Colors, DesignTokens, Radius, Rgba, Spacing, Typography};
use crate::foundation::object_model::types::{
    ApiOperation, DefaultChildView, DefaultSort, EdgeBehavior, EdgeCascade, EdgeScope,
    EntityFieldType, EnumOption, RollupFunction, SortDir, TabDefinition, UiHints,
};
use crate::kernel::config::types::{SettingScope, SettingType};
use crate::shell_mode::{Permission, ShellMode};

/// Every Luau-exposed type defined in `prism-core`. Each entry is
/// `(luau type name, full `export type` declaration)`.
///
/// Hand-rolled bindings from [`crate::luau_bindings`] (the
/// `GraphObject` / `ObjectEdge` userdata + the `Objects` / `Config`
/// service handles) are appended unconditionally — the type stubs
/// themselves are plain string constants, so they compile even when
/// the `luau` feature is off and the runtime impls aren't built.
pub fn type_defs() -> Vec<(&'static str, &'static str)> {
    let mut defs = crate::luau_types![
        // design tokens
        DesignTokens,
        Colors,
        Spacing,
        Radius,
        Typography,
        Rgba,
        // shell mode
        ShellMode,
        Permission,
        // object-model leaves
        EntityFieldType,
        RollupFunction,
        EnumOption,
        UiHints,
        EdgeBehavior,
        EdgeScope,
        EdgeCascade,
        DefaultChildView,
        TabDefinition,
        ApiOperation,
        DefaultSort,
        SortDir,
        // config leaves
        SettingScope,
        SettingType,
    ];
    // Hand-rolled stateful surfaces — the userdata types in
    // `luau_bindings.rs` aren't `#[luau_expose]`-derived, so they
    // expose their LUAU_TYPE_NAME/DEF as free `pub const`s rather than
    // associated items. The macro can't reach those, so they're
    // appended here.
    defs.extend_from_slice(&[
        (
            crate::luau_bindings_consts::GRAPH_OBJECT_TYPE_NAME,
            crate::luau_bindings_consts::GRAPH_OBJECT_TYPE_DEF,
        ),
        (
            crate::luau_bindings_consts::OBJECT_EDGE_TYPE_NAME,
            crate::luau_bindings_consts::OBJECT_EDGE_TYPE_DEF,
        ),
        (
            crate::luau_bindings_consts::OBJECTS_HANDLE_TYPE_NAME,
            crate::luau_bindings_consts::OBJECTS_HANDLE_TYPE_DEF,
        ),
        (
            crate::luau_bindings_consts::EDGES_HANDLE_TYPE_NAME,
            crate::luau_bindings_consts::EDGES_HANDLE_TYPE_DEF,
        ),
        (
            crate::luau_bindings_consts::CONFIG_HANDLE_TYPE_NAME,
            crate::luau_bindings_consts::CONFIG_HANDLE_TYPE_DEF,
        ),
        // Phase 5 of `docs/dev/dioxus-inspiration.md`: reactive
        // substrate userdata. Bindings live in
        // `crate::luau_reactive` (feature-gated), constants live
        // unconditionally in `luau_bindings_consts` so the codegen
        // pipeline can pick them up without the `luau` feature.
        (
            crate::luau_bindings_consts::REACTIVE_SIGNAL_TYPE_NAME,
            crate::luau_bindings_consts::REACTIVE_SIGNAL_TYPE_DEF,
        ),
        (
            crate::luau_bindings_consts::REACTIVE_MEMO_TYPE_NAME,
            crate::luau_bindings_consts::REACTIVE_MEMO_TYPE_DEF,
        ),
    ]);
    defs
}

/// Concatenate every entry from [`type_defs`] into a single Luau source
/// file, prefixed with `--!strict`. Stable ordering: matches the slice
/// order, which is curated leaf-first so dependent types declare after
/// their dependencies. Luau's type checker is order-insensitive within
/// a file, but readers aren't.
pub fn render_type_stubs() -> String {
    let mut out = String::from(
        "--!strict\n-- Generated by `prism codegen luau-types`. Do not edit by hand.\n\n",
    );
    for (_, def) in type_defs() {
        out.push_str(def);
        out.push_str("\n\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_design_token_type_is_registered() {
        let names: Vec<&str> = type_defs().iter().map(|(n, _)| *n).collect();
        for expected in [
            "DesignTokens",
            "Colors",
            "Spacing",
            "Radius",
            "Typography",
            "Rgba",
        ] {
            assert!(
                names.contains(&expected),
                "missing {expected} from luau type registry"
            );
        }
    }

    #[test]
    fn rgba_def_describes_four_u8_fields_as_numbers() {
        assert_eq!(
            Rgba::LUAU_TYPE_DEF,
            "export type Rgba = {\n    r: number,\n    g: number,\n    b: number,\n    a: number,\n}"
        );
    }

    #[test]
    fn design_tokens_def_references_nested_types_by_name() {
        let def = DesignTokens::LUAU_TYPE_DEF;
        assert!(def.contains("colors: Colors"));
        assert!(def.contains("spacing: Spacing"));
        assert!(def.contains("radius: Radius"));
        assert!(def.contains("typography: Typography"));
    }

    #[test]
    fn shell_mode_def_is_string_union() {
        assert_eq!(
            ShellMode::LUAU_TYPE_DEF,
            "export type ShellMode = \"Use\" | \"Build\" | \"Admin\""
        );
    }

    #[test]
    fn entity_field_type_is_registered_as_union() {
        assert!(EntityFieldType::LUAU_TYPE_DEF.contains("\"Bool\""));
        assert!(EntityFieldType::LUAU_TYPE_DEF.contains("\"Datetime\""));
    }

    #[test]
    fn graph_object_def_is_registered() {
        let names: Vec<&str> = type_defs().iter().map(|(n, _)| *n).collect();
        assert!(names.contains(&"GraphObject"));
        assert!(names.contains(&"ObjectEdge"));
        assert!(names.contains(&"Objects"));
        assert!(names.contains(&"Edges"));
        assert!(names.contains(&"Config"));
    }

    #[test]
    fn reactive_substrate_types_are_registered() {
        let names: Vec<&str> = type_defs().iter().map(|(n, _)| *n).collect();
        assert!(names.contains(&"Signal"), "Signal type stub missing");
        assert!(names.contains(&"Memo"), "Memo type stub missing");
    }

    #[test]
    fn render_type_stubs_emits_strict_header_and_every_def() {
        let rendered = render_type_stubs();
        assert!(rendered.starts_with("--!strict\n"));
        for (_, def) in type_defs() {
            assert!(rendered.contains(def), "stub missing: {def}");
        }
    }
}
