//! Hand-maintained registry of every type in `prism-core` that has been
//! annotated with `#[luau_expose]` or hand-rolled in
//! [`crate::luau_bindings`]. The codegen subcommand (`prism codegen
//! luau-types`) walks this slice to produce the consolidated `.d.luau`
//! stub tree described in `docs/dev/luau-integration-plan.md` §Phase 5.
//!
//! Why a hand list instead of `inventory!`-style link-time collection:
//! the daemon is built as `cdylib` + `staticlib` + WASM, where
//! distributed slice strategies are flaky. A plain function returning
//! `&[(&str, &str)]` works on every target and stays trivial to audit.
//! Add a new entry here whenever a new annotation lands.

use crate::design_tokens::{Colors, DesignTokens, Radius, Rgba, Spacing, Typography};
use crate::foundation::object_model::types::{
    ApiOperation, DefaultChildView, DefaultSort, EdgeBehavior, EdgeCascade, EdgeScope,
    EntityFieldType, EnumOption, RollupFunction, SortDir, TabDefinition, UiHints,
};
use crate::kernel::config::types::{SettingScope, SettingType};
use crate::shell_mode::{Permission, ShellMode};

/// Every Luau-exposed type defined in `prism-core`. Each entry is
/// `(luau type name, full `export type` declaration)`.
///
/// Hand-rolled bindings from [`crate::luau_bindings`] (the
/// `GraphObject` / `ObjectEdge` userdata + the `Objects` / `Config`
/// service handles) are appended unconditionally — the type stubs
/// themselves are plain string constants, so they compile even when
/// the `luau` feature is off and the runtime impls aren't built.
pub fn type_defs() -> Vec<(&'static str, &'static str)> {
    vec![
        // ── design tokens ────────────────────────────────────────
        (DesignTokens::LUAU_TYPE_NAME, DesignTokens::LUAU_TYPE_DEF),
        (Colors::LUAU_TYPE_NAME, Colors::LUAU_TYPE_DEF),
        (Spacing::LUAU_TYPE_NAME, Spacing::LUAU_TYPE_DEF),
        (Radius::LUAU_TYPE_NAME, Radius::LUAU_TYPE_DEF),
        (Typography::LUAU_TYPE_NAME, Typography::LUAU_TYPE_DEF),
        (Rgba::LUAU_TYPE_NAME, Rgba::LUAU_TYPE_DEF),
        // ── shell mode ───────────────────────────────────────────
        (ShellMode::LUAU_TYPE_NAME, ShellMode::LUAU_TYPE_DEF),
        (Permission::LUAU_TYPE_NAME, Permission::LUAU_TYPE_DEF),
        // ── object-model leaves ──────────────────────────────────
        (
            EntityFieldType::LUAU_TYPE_NAME,
            EntityFieldType::LUAU_TYPE_DEF,
        ),
        (
            RollupFunction::LUAU_TYPE_NAME,
            RollupFunction::LUAU_TYPE_DEF,
        ),
        (EnumOption::LUAU_TYPE_NAME, EnumOption::LUAU_TYPE_DEF),
        (UiHints::LUAU_TYPE_NAME, UiHints::LUAU_TYPE_DEF),
        (EdgeBehavior::LUAU_TYPE_NAME, EdgeBehavior::LUAU_TYPE_DEF),
        (EdgeScope::LUAU_TYPE_NAME, EdgeScope::LUAU_TYPE_DEF),
        (EdgeCascade::LUAU_TYPE_NAME, EdgeCascade::LUAU_TYPE_DEF),
        (
            DefaultChildView::LUAU_TYPE_NAME,
            DefaultChildView::LUAU_TYPE_DEF,
        ),
        (TabDefinition::LUAU_TYPE_NAME, TabDefinition::LUAU_TYPE_DEF),
        (ApiOperation::LUAU_TYPE_NAME, ApiOperation::LUAU_TYPE_DEF),
        (DefaultSort::LUAU_TYPE_NAME, DefaultSort::LUAU_TYPE_DEF),
        (SortDir::LUAU_TYPE_NAME, SortDir::LUAU_TYPE_DEF),
        // ── config leaves ────────────────────────────────────────
        (SettingScope::LUAU_TYPE_NAME, SettingScope::LUAU_TYPE_DEF),
        (SettingType::LUAU_TYPE_NAME, SettingType::LUAU_TYPE_DEF),
        // ── hand-rolled stateful surfaces ────────────────────────
        (
            crate::luau_bindings_consts::GRAPH_OBJECT_TYPE_NAME,
            crate::luau_bindings_consts::GRAPH_OBJECT_TYPE_DEF,
        ),
        (
            crate::luau_bindings_consts::OBJECT_EDGE_TYPE_NAME,
            crate::luau_bindings_consts::OBJECT_EDGE_TYPE_DEF,
        ),
        (
            crate::luau_bindings_consts::OBJECTS_HANDLE_TYPE_NAME,
            crate::luau_bindings_consts::OBJECTS_HANDLE_TYPE_DEF,
        ),
        (
            crate::luau_bindings_consts::CONFIG_HANDLE_TYPE_NAME,
            crate::luau_bindings_consts::CONFIG_HANDLE_TYPE_DEF,
        ),
    ]
}

/// Concatenate every entry from [`type_defs`] into a single Luau source
/// file, prefixed with `--!strict`. Stable ordering: matches the slice
/// order, which is curated leaf-first so dependent types declare after
/// their dependencies. Luau's type checker is order-insensitive within
/// a file, but readers aren't.
pub fn render_type_stubs() -> String {
    let mut out = String::from(
        "--!strict\n-- Generated by `prism codegen luau-types`. Do not edit by hand.\n\n",
    );
    for (_, def) in type_defs() {
        out.push_str(def);
        out.push_str("\n\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_design_token_type_is_registered() {
        let names: Vec<&str> = type_defs().iter().map(|(n, _)| *n).collect();
        for expected in [
            "DesignTokens",
            "Colors",
            "Spacing",
            "Radius",
            "Typography",
            "Rgba",
        ] {
            assert!(
                names.contains(&expected),
                "missing {expected} from luau type registry"
            );
        }
    }

    #[test]
    fn rgba_def_describes_four_u8_fields_as_numbers() {
        assert_eq!(
            Rgba::LUAU_TYPE_DEF,
            "export type Rgba = {\n    r: number,\n    g: number,\n    b: number,\n    a: number,\n}"
        );
    }

    #[test]
    fn design_tokens_def_references_nested_types_by_name() {
        let def = DesignTokens::LUAU_TYPE_DEF;
        assert!(def.contains("colors: Colors"));
        assert!(def.contains("spacing: Spacing"));
        assert!(def.contains("radius: Radius"));
        assert!(def.contains("typography: Typography"));
    }

    #[test]
    fn shell_mode_def_is_string_union() {
        assert_eq!(
            ShellMode::LUAU_TYPE_DEF,
            "export type ShellMode = \"Use\" | \"Build\" | \"Admin\""
        );
    }

    #[test]
    fn entity_field_type_is_registered_as_union() {
        assert!(EntityFieldType::LUAU_TYPE_DEF.contains("\"Bool\""));
        assert!(EntityFieldType::LUAU_TYPE_DEF.contains("\"Datetime\""));
    }

    #[test]
    fn graph_object_def_is_registered() {
        let names: Vec<&str> = type_defs().iter().map(|(n, _)| *n).collect();
        assert!(names.contains(&"GraphObject"));
        assert!(names.contains(&"ObjectEdge"));
        assert!(names.contains(&"Objects"));
        assert!(names.contains(&"Config"));
    }

    #[test]
    fn render_type_stubs_emits_strict_header_and_every_def() {
        let rendered = render_type_stubs();
        assert!(rendered.starts_with("--!strict\n"));
        for (_, def) in type_defs() {
            assert!(rendered.contains(def), "stub missing: {def}");
        }
    }
}
