//! Canonical keyword tables — declaration kinds, syntactic-directive
//! names, builtin directive verbs, contract keys, scene-heading
//! prefixes, and the line-marker glyphs the lexer dispatches on.
//!
//! This table is the **single source of truth** for both the parser
//! and every external editor surface ([`loom-syntax`] emits the
//! TextMate grammar from these lists; the web editor's CodeMirror
//! `StreamLanguage` is generated by the same constants compiled to
//! wasm). Adding a syntactic form here propagates to every editor on
//! the next build.
//!
//! Spec cross-references:
//! * §5  — five-bracket discipline
//! * §6  — declaration / beat shape
//! * §7  — diverts and tunnels
//! * §10 — Simulacra (characters)
//! * §11 — Meridian (stats)
//! * §14 — directives

use crate::ast::DeclarationKind;

/// `KEYWORD Name [is …]` declaration openers (spec §6, §10, §11).
///
/// Ordered to match [`DeclarationKind`]; the lexer dispatches on the
/// first whitespace-delimited word and matches against this list.
pub const DECLARATIONS: &[&str] = &[
    "CHARACTER",
    "TRAIT",
    "ITEM",
    "LOCATION",
    "FACTION",
    "STATS",
    "TREE",
    "GENERATOR",
    "SCENE",
    "COHORT",
];

/// Directive verbs whose **shape** is part of the grammar (spec §14.2).
///
/// Unlike free Luau directives (`<sfx: bell>`), these are recognised
/// structurally by the parser: `<if:>`/`<else if:>`/`<else>` form a
/// chain, `<for:>` opens an iteration body, `<after:>` opens a delayed
/// block, `<each visit>` runs once-per-visit, etc.
pub const SYNTACTIC_DIRECTIVES: &[&str] = &[
    "if",
    "else if",
    "else",
    "match",
    "case",
    "for",
    "each visit",
    "after",
    "otherwise",
    "anchor",
    "let",
];

/// Builtin directive verbs registered by `loom_runtime::builtins`.
/// Highlighted distinctly so authors can tell core verbs from
/// project-defined Luau directives at a glance.
pub const BUILTIN_DIRECTIVES: &[&str] = &["sfx", "cue", "pause", "anchor", "fire", "set"];

/// Contract-zone property keys that have grammar-level meaning under a
/// `==` knot opener or beat heading (spec §6, §13).
///
/// The lexer recognises any `key: value` line; this list drives
/// **highlighting** so reserved beat contract keys read distinctly
/// from arbitrary author-defined properties.
pub const CONTRACT_KEYS: &[&str] = &[
    "cast",
    "setting",
    "with topic",
    "with",
    "entry",
    "tags",
    "title",
    "author",
    "next",
];

/// Fountain-style scene-heading prefixes (spec §6).
///
/// Recognition is anchored to the start of the line; the lexer
/// matches on `text.starts_with(prefix)`.
pub const SCENE_HEADING_PREFIXES: &[&str] = &["INT.", "EXT.", "INT/EXT", "INT./EXT.", "I/E "];

/// Reserved keyword words that appear *inside* lines (not as openers):
/// `let`, `is` (mixin), `with` (divert parameters), `END` (divert
/// target).
pub const RESERVED_INLINE: &[&str] = &["let", "is", "with", "END"];

/// Stable line-marker glyphs the lexer dispatches on (spec §2, §5).
pub mod markers {
    pub const HEADING: &str = "#";
    pub const KNOT: &str = "==";
    pub const CHOICE_ONCE: &str = "*";
    pub const CHOICE_STICKY: &str = "+";
    pub const DIVERT: &str = "->";
    pub const TUNNEL_RETURN: &str = "<-";
    pub const FENCE: &str = "```";
    pub const DIRECTIVE_OPEN: char = '<';
    pub const DIRECTIVE_CLOSE: char = '>';
    pub const INTERPOLATION_OPEN: char = '{';
    pub const INTERPOLATION_CLOSE: char = '}';
    pub const SUPPRESSION_OPEN: char = '[';
    pub const SUPPRESSION_CLOSE: char = ']';
    pub const PARENTHETICAL_OPEN: char = '(';
    pub const PARENTHETICAL_CLOSE: char = ')';
    /// `//` line comment opener (spec §6.1).
    pub const LINE_COMMENT: &str = "//";
    /// `/*` block comment opener (spec §6.1).
    pub const BLOCK_COMMENT_OPEN: &str = "/*";
    /// `*/` block comment closer (spec §6.1).
    pub const BLOCK_COMMENT_CLOSE: &str = "*/";
}

/// Looks up a declaration keyword without allocating; a thin wrapper
/// over [`DeclarationKind::from_keyword`] kept in this module so
/// downstream tooling (LSP, syntax codegen) has one stable import
/// path.
pub fn declaration_kind(word: &str) -> Option<DeclarationKind> {
    DeclarationKind::from_keyword(word)
}

/// Every declaration keyword paired with its [`DeclarationKind`].
/// Used by the TextMate grammar emitter to attach distinct scope
/// names per kind (e.g. `entity.name.type.character.loom`).
pub fn declarations_with_kind() -> impl Iterator<Item = (&'static str, DeclarationKind)> {
    use DeclarationKind::*;
    [
        ("CHARACTER", Character),
        ("TRAIT", Trait),
        ("ITEM", Item),
        ("LOCATION", Location),
        ("FACTION", Faction),
        ("STATS", Stats),
        ("TREE", Tree),
        ("GENERATOR", Generator),
        ("SCENE", Scene),
        ("COHORT", Cohort),
    ]
    .into_iter()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn declarations_round_trip_through_ast() {
        for word in DECLARATIONS {
            let kind = declaration_kind(word).expect("declaration keyword resolves");
            assert_eq!(kind.keyword(), *word, "AST and table disagree on `{word}`");
        }
    }

    #[test]
    fn declarations_match_ast_count() {
        // If a new variant is added to DeclarationKind, this assertion
        // forces the table to stay in lockstep.
        let ast_count = declarations_with_kind().count();
        assert_eq!(ast_count, DECLARATIONS.len());
    }

    #[test]
    fn directive_lists_are_non_empty() {
        // `anchor` deliberately appears in both — it's structurally
        // recognised by the parser (spec §14.2) and the runtime also
        // registers a default handler for it (`builtins::register`).
        // The grammar emitter dedupes when colouring.
        assert!(!SYNTACTIC_DIRECTIVES.is_empty());
        assert!(!BUILTIN_DIRECTIVES.is_empty());
    }
}
