//! Concrete `SymbolEmitter` implementations — TS, C#, EmmyDoc, GDScript.
//!
//! Port of `language/codegen/symbol-emitter.ts`. The TS version used
//! a `SymbolEmitter` base class with protected override points; the
//! Rust port uses plain structs that implement [`Emitter`] directly
//! and share pattern via private free functions. No class hierarchy,
//! no dynamic dispatch between subclasses — each emitter owns its
//! whole format.
//!
//! Every emitter accepts `Vec<SymbolDef>` via the shared
//! [`EMITTER_KIND_SYMBOLS`](super::types::EMITTER_KIND_SYMBOLS) slot
//! on [`CodegenInputs`](super::types::CodegenInputs).

use super::source_builder::SourceBuilder;
use super::symbol_def::{SymbolDef, SymbolKind, SymbolParam};
use super::types::{CodegenMeta, CodegenResult, EmittedFile, Emitter, EMITTER_KIND_SYMBOLS};
use crate::language::syntax::case_utils::{
    to_camel_case, to_pascal_case, to_screaming_snake, to_snake_case,
};
use serde_json::Value as JsonValue;

/// Rename hook applied to every symbol name. Lets the same
/// [`SymbolDef`] tree render as `camelCase` TS, `PascalCase` C#, and
/// `SCREAMING_SNAKE_CASE` GDScript constants without mutating the
/// source of truth.
pub type NameTransform = fn(&str, SymbolKind) -> String;

fn transform(name: &str, kind: SymbolKind, t: Option<NameTransform>) -> String {
    match t {
        Some(f) => f(name, kind),
        None => name.to_owned(),
    }
}

fn downcast_symbols(input: &dyn std::any::Any) -> Option<&Vec<SymbolDef>> {
    input.downcast_ref::<Vec<SymbolDef>>()
}

fn js_literal(value: Option<&JsonValue>) -> String {
    match value {
        Some(JsonValue::String(s)) => format!("'{s}'"),
        Some(v) => v.to_string(),
        None => "undefined".into(),
    }
}

fn param_list(params: &[SymbolParam]) -> String {
    params
        .iter()
        .map(|p| {
            format!(
                "{}{}: {}",
                p.name,
                if p.optional { "?" } else { "" },
                p.r#type
            )
        })
        .collect::<Vec<_>>()
        .join(", ")
}

// ── TypeScript emitter ─────────────────────────────────────────────

/// TypeScript emitter. Produces `export const` constants, `declare
/// function` signatures, `interface` blocks for classes, and nested
/// `as const` objects for namespaces. Matches the TS output from
/// `SymbolTypeScriptEmitter` line-for-line.
#[derive(Debug, Default, Clone)]
pub struct SymbolTypeScriptEmitter {
    pub module_name: Option<String>,
    pub filename: Option<String>,
    pub name_transform: Option<NameTransform>,
}

impl SymbolTypeScriptEmitter {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_module_name(mut self, module_name: impl Into<String>) -> Self {
        self.module_name = Some(module_name.into());
        self
    }

    pub fn with_filename(mut self, filename: impl Into<String>) -> Self {
        self.filename = Some(filename.into());
        self
    }

    pub fn with_name_transform(mut self, transform: NameTransform) -> Self {
        self.name_transform = Some(transform);
        self
    }

    fn filename_for(&self, meta: &CodegenMeta) -> String {
        self.filename.clone().unwrap_or_else(|| {
            format!(
                "{}.g.ts",
                self.module_name.as_deref().unwrap_or(&meta.project_name)
            )
        })
    }

    fn emit_header(&self, b: &mut SourceBuilder, meta: &CodegenMeta) {
        b.line(format!(
            "// Generated by Prism Codegen — {}",
            meta.project_name
        ));
        b.line("// Do not edit manually. Re-run the build to regenerate.");
        b.line("/* eslint-disable */");
    }

    fn emit_symbol(&self, b: &mut SourceBuilder, sym: &SymbolDef, depth: usize) {
        let indent = depth > 0;
        match sym.kind {
            SymbolKind::Constant => self.emit_constant(b, sym, indent),
            SymbolKind::Namespace => self.emit_namespace(b, sym, depth),
            SymbolKind::Enum => self.emit_enum(b, sym, indent),
            SymbolKind::Function => self.emit_function(b, sym, indent),
            SymbolKind::Class => self.emit_class(b, sym, indent),
            SymbolKind::Field => self.emit_field(b, sym),
        }
    }

    fn doc(&self, b: &mut SourceBuilder, text: Option<&String>) {
        if let Some(t) = text {
            b.line(format!("/** {t} */"));
        }
    }

    fn emit_constant(&self, b: &mut SourceBuilder, sym: &SymbolDef, indent: bool) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        self.doc(b, sym.description.as_ref());
        let val = js_literal(sym.value.as_ref());
        if indent {
            b.line(format!("{name}: {val},"));
        } else {
            b.line(format!("export const {name} = {val} as const;"));
        }
    }

    fn emit_namespace(&self, b: &mut SourceBuilder, sym: &SymbolDef, depth: usize) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        self.doc(b, sym.description.as_ref());
        if depth == 0 {
            b.line(format!("export const {name} = {{"));
        } else {
            b.line(format!("{name}: {{"));
        }
        b.indent();
        for child in &sym.children {
            self.emit_symbol(b, child, depth + 1);
        }
        b.dedent();
        b.line(if depth == 0 { "} as const;" } else { "}," });
    }

    fn emit_enum(&self, b: &mut SourceBuilder, sym: &SymbolDef, indent: bool) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        self.doc(b, sym.description.as_ref());
        let export = if indent { "" } else { "export " };
        b.line(format!("{export}const {name} = {{"));
        b.indent();
        for v in &sym.enum_values {
            if let Some(desc) = &v.description {
                b.line(format!("/** {desc} */"));
            }
            let val = js_literal(Some(&v.value));
            b.line(format!("{}: {val},", v.name));
        }
        b.dedent();
        b.line("} as const;");
        b.line(format!(
            "{export}type {name} = typeof {name}[keyof typeof {name}];"
        ));
    }

    fn emit_function(&self, b: &mut SourceBuilder, sym: &SymbolDef, indent: bool) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        self.doc(b, sym.description.as_ref());
        if let Some(d) = &sym.deprecated {
            b.line(format!("/** @deprecated {d} */"));
        }
        let params = param_list(&sym.params);
        let ret = sym.returns.as_deref().unwrap_or("void");
        let async_ = if sym.async_ { "async " } else { "" };
        let export = if indent { "" } else { "export " };
        b.line(format!(
            "{export}declare {async_}function {name}({params}): {ret};"
        ));
    }

    fn emit_class(&self, b: &mut SourceBuilder, sym: &SymbolDef, indent: bool) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        self.doc(b, sym.description.as_ref());
        let export = if indent { "" } else { "export " };
        b.line(format!("{export}interface {name} {{"));
        b.indent();
        for child in &sym.children {
            self.emit_symbol(b, child, 1);
        }
        b.dedent();
        b.line("}");
    }

    fn emit_field(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        self.doc(b, sym.description.as_ref());
        let raw = sym.r#type.as_deref().unwrap_or("unknown");
        let (type_, opt) = if let Some(stripped) = raw.strip_suffix('?') {
            (stripped, "?")
        } else {
            (raw, "")
        };
        b.line(format!("{name}{opt}: {type_};"));
    }
}

impl Emitter for SymbolTypeScriptEmitter {
    fn id(&self) -> &str {
        "symbol-typescript"
    }
    fn input_kind(&self) -> &str {
        EMITTER_KIND_SYMBOLS
    }
    fn emit(&self, input: &dyn std::any::Any, meta: &CodegenMeta) -> CodegenResult {
        let Some(symbols) = downcast_symbols(input) else {
            return CodegenResult {
                files: vec![],
                errors: vec!["expected Vec<SymbolDef>".into()],
            };
        };
        let mut b = SourceBuilder::default();
        self.emit_header(&mut b, meta);
        b.blank();
        for sym in symbols {
            b.blank();
            self.emit_symbol(&mut b, sym, 0);
        }
        CodegenResult {
            files: vec![EmittedFile {
                filename: self.filename_for(meta),
                content: b.build(),
                language: "typescript".into(),
            }],
            errors: vec![],
        }
    }
}

// ── C# emitter ─────────────────────────────────────────────────────

/// C# emitter. Wraps every symbol in a namespace block and emits
/// `public static class` containers for namespaces.
#[derive(Debug, Default, Clone)]
pub struct SymbolCSharpEmitter {
    pub namespace: Option<String>,
    pub class_name: Option<String>,
    pub filename: Option<String>,
    pub name_transform: Option<NameTransform>,
}

impl SymbolCSharpEmitter {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_namespace(mut self, namespace: impl Into<String>) -> Self {
        self.namespace = Some(namespace.into());
        self
    }

    pub fn with_class_name(mut self, class_name: impl Into<String>) -> Self {
        self.class_name = Some(class_name.into());
        self
    }

    pub fn with_name_transform(mut self, transform: NameTransform) -> Self {
        self.name_transform = Some(transform);
        self
    }

    fn filename_for(&self, meta: &CodegenMeta) -> String {
        self.filename.clone().unwrap_or_else(|| {
            format!(
                "{}.g.cs",
                self.class_name.as_deref().unwrap_or(&meta.project_name)
            )
        })
    }

    fn cs_type(type_: Option<&str>) -> String {
        match type_ {
            None => "object".into(),
            Some("string") => "string".into(),
            Some("number") => "float".into(),
            Some("boolean") => "bool".into(),
            Some("void") => "void".into(),
            Some(other) => other.to_owned(),
        }
    }

    fn cs_literal(value: Option<&JsonValue>) -> String {
        match value {
            Some(JsonValue::String(s)) => format!("\"{s}\""),
            Some(v) => v.to_string(),
            None => "null".into(),
        }
    }

    fn xml_doc(b: &mut SourceBuilder, text: Option<&String>) {
        if let Some(t) = text {
            b.line(format!("/// <summary>{t}</summary>"));
        }
    }

    fn emit_symbol(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        match sym.kind {
            SymbolKind::Constant => self.emit_constant(b, sym),
            SymbolKind::Namespace => self.emit_namespace(b, sym),
            SymbolKind::Enum => self.emit_enum(b, sym),
            SymbolKind::Function => self.emit_method(b, sym),
            SymbolKind::Class => self.emit_class(b, sym),
            SymbolKind::Field => self.emit_field(b, sym),
        }
    }

    fn emit_constant(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::xml_doc(b, sym.description.as_ref());
        let type_ = Self::cs_type(sym.r#type.as_deref().or(Some("string")));
        let val = Self::cs_literal(sym.value.as_ref());
        b.line(format!("public const {type_} {name} = {val};"));
    }

    fn emit_namespace(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::xml_doc(b, sym.description.as_ref());
        b.line(format!("public static class {name}"));
        b.line("{");
        b.indent();
        for child in &sym.children {
            self.emit_symbol(b, child);
        }
        b.dedent();
        b.line("}");
    }

    fn emit_enum(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::xml_doc(b, sym.description.as_ref());
        b.line(format!("public enum {name}"));
        b.line("{");
        b.indent();
        for v in &sym.enum_values {
            if let Some(desc) = &v.description {
                b.line(format!("/// <summary>{desc}</summary>"));
            }
            b.line(format!("{},", v.name));
        }
        b.dedent();
        b.line("}");
    }

    fn emit_method(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::xml_doc(b, sym.description.as_ref());
        let params = sym
            .params
            .iter()
            .map(|p| format!("{} {}", Self::cs_type(Some(&p.r#type)), p.name))
            .collect::<Vec<_>>()
            .join(", ");
        let ret = Self::cs_type(sym.returns.as_deref().or(Some("void")));
        b.line(format!("public static {ret} {name}({params}) {{ }}"));
    }

    fn emit_class(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::xml_doc(b, sym.description.as_ref());
        b.line(format!("public class {name}"));
        b.line("{");
        b.indent();
        for child in &sym.children {
            self.emit_symbol(b, child);
        }
        b.dedent();
        b.line("}");
    }

    fn emit_field(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::xml_doc(b, sym.description.as_ref());
        b.line(format!(
            "public {} {name};",
            Self::cs_type(sym.r#type.as_deref())
        ));
    }
}

impl Emitter for SymbolCSharpEmitter {
    fn id(&self) -> &str {
        "symbol-csharp"
    }
    fn input_kind(&self) -> &str {
        EMITTER_KIND_SYMBOLS
    }
    fn emit(&self, input: &dyn std::any::Any, meta: &CodegenMeta) -> CodegenResult {
        let Some(symbols) = downcast_symbols(input) else {
            return CodegenResult {
                files: vec![],
                errors: vec!["expected Vec<SymbolDef>".into()],
            };
        };
        let mut b = SourceBuilder::default();
        b.line(format!(
            "// Generated by Prism Codegen — {}",
            meta.project_name
        ));
        b.line("// Do not edit manually. Re-run the build to regenerate.");
        b.blank();
        let ns = self.namespace.as_deref().unwrap_or("Prism");
        b.line(format!("namespace {ns}"));
        b.line("{");
        b.indent();
        for sym in symbols {
            b.blank();
            self.emit_symbol(&mut b, sym);
        }
        b.dedent();
        b.line("}");
        CodegenResult {
            files: vec![EmittedFile {
                filename: self.filename_for(meta),
                content: b.build(),
                language: "csharp".into(),
            }],
            errors: vec![],
        }
    }
}

// ── EmmyDoc (Luau) emitter ─────────────────────────────────────────

/// LuaLS-compatible `.d.luau` type-stub emitter. Produces
/// `---@class` / `---@field` / `---@param` annotations and empty
/// `function NS.Name(...) end` bodies.
#[derive(Debug, Default, Clone)]
pub struct SymbolEmmyDocEmitter {
    pub global_name: Option<String>,
    pub filename: Option<String>,
    pub name_transform: Option<NameTransform>,
    /// When set, emit a trailing `return <table>` line.
    pub return_table: Option<String>,
}

impl SymbolEmmyDocEmitter {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn with_global_name(mut self, name: impl Into<String>) -> Self {
        self.global_name = Some(name.into());
        self
    }

    pub fn with_return_table(mut self, name: impl Into<String>) -> Self {
        self.return_table = Some(name.into());
        self
    }

    fn filename_for(&self, meta: &CodegenMeta) -> String {
        self.filename.clone().unwrap_or_else(|| {
            format!(
                "{}.d.luau",
                self.global_name.as_deref().unwrap_or(&meta.project_name)
            )
        })
    }

    fn emit_symbol(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let ns = self.global_name.as_deref();
        match sym.kind {
            SymbolKind::Constant => self.emit_constant(b, sym, ns),
            SymbolKind::Namespace => self.emit_namespace(b, sym),
            SymbolKind::Enum => self.emit_enum(b, sym),
            SymbolKind::Function => Self::emit_function(b, sym, ns, self.name_transform),
            SymbolKind::Class => self.emit_class(b, sym),
            SymbolKind::Field => {} // handled inside namespace/class
        }
    }

    fn emit_constant(&self, b: &mut SourceBuilder, sym: &SymbolDef, ns: Option<&str>) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        if let Some(desc) = &sym.description {
            b.line(format!("--- {desc}"));
        }
        b.line(format!(
            "---@type {}",
            sym.r#type.as_deref().unwrap_or("unknown")
        ));
        let qual = ns.map(|n| format!("{n}.")).unwrap_or_default();
        b.line(format!("{qual}{name} = nil"));
    }

    fn field_type(sym: &SymbolDef) -> String {
        match sym.kind {
            SymbolKind::Function => {
                let params = sym
                    .params
                    .iter()
                    .map(|p| format!("{}: {}", p.name, p.r#type))
                    .collect::<Vec<_>>()
                    .join(", ");
                let ret = sym
                    .returns
                    .as_deref()
                    .map(|r| format!(": {r}"))
                    .unwrap_or_default();
                format!("fun({params}){ret}")
            }
            SymbolKind::Constant => sym.r#type.clone().unwrap_or_else(|| "unknown".into()),
            SymbolKind::Namespace | SymbolKind::Class => sym.name.clone(),
            _ => "unknown".into(),
        }
    }

    fn emit_namespace(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        if let Some(desc) = &sym.description {
            b.line(format!("--- {desc}"));
        }
        b.line(format!("---@class {name}"));
        for child in &sym.children {
            let child_name = transform(&child.name, child.kind, self.name_transform);
            let type_str = Self::field_type(child);
            let desc = child
                .description
                .as_ref()
                .map(|d| format!(" # {d}"))
                .unwrap_or_default();
            b.line(format!("---@field {child_name} {type_str}{desc}"));
        }
        b.line(format!("{name} = {{}}"));
        b.blank();
        for child in &sym.children {
            if child.kind == SymbolKind::Function {
                Self::emit_function(b, child, Some(&name), self.name_transform);
                b.blank();
            }
        }
        for child in &sym.children {
            if matches!(
                child.kind,
                SymbolKind::Namespace | SymbolKind::Class | SymbolKind::Enum
            ) {
                self.emit_symbol(b, child);
                b.blank();
            }
        }
    }

    fn emit_enum(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        if let Some(desc) = &sym.description {
            b.line(format!("--- {desc}"));
        }
        b.line(format!("---@alias {name}"));
        for v in &sym.enum_values {
            let val = match &v.value {
                JsonValue::String(s) => format!("\"{s}\""),
                other => other.to_string(),
            };
            let desc = v
                .description
                .as_ref()
                .map(|d| format!(" — {d}"))
                .unwrap_or_default();
            b.line(format!("---| {val} # {}{desc}", v.name));
        }
        b.line("");
    }

    fn emit_function(
        b: &mut SourceBuilder,
        sym: &SymbolDef,
        ns: Option<&str>,
        tr: Option<NameTransform>,
    ) {
        let name = transform(&sym.name, sym.kind, tr);
        if let Some(desc) = &sym.description {
            b.line(format!("--- {desc}"));
        }
        if let Some(d) = &sym.deprecated {
            b.line(format!("---@deprecated {d}"));
        }
        for p in &sym.params {
            let opt = if p.optional { "?" } else { "" };
            let desc = p
                .description
                .as_ref()
                .map(|d| format!(" # {d}"))
                .unwrap_or_default();
            b.line(format!("---@param {}{opt} {}{desc}", p.name, p.r#type));
        }
        if let Some(r) = &sym.returns {
            b.line(format!("---@return {r}"));
        }
        let params = sym
            .params
            .iter()
            .map(|p| p.name.clone())
            .collect::<Vec<_>>()
            .join(", ");
        let qual = ns.map(|n| format!("{n}.")).unwrap_or_default();
        b.line(format!("function {qual}{name}({params}) end"));
    }

    fn emit_class(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        if let Some(desc) = &sym.description {
            b.line(format!("--- {desc}"));
        }
        b.line(format!("---@class {name}"));
        for child in &sym.children {
            if child.kind == SymbolKind::Field {
                let child_name = transform(&child.name, child.kind, self.name_transform);
                let desc = child
                    .description
                    .as_ref()
                    .map(|d| format!(" # {d}"))
                    .unwrap_or_default();
                b.line(format!(
                    "---@field {child_name} {}{desc}",
                    child.r#type.as_deref().unwrap_or("unknown")
                ));
            }
        }
        b.line(format!("local {name} = {{}}"));
        b.blank();
        for child in &sym.children {
            if child.kind == SymbolKind::Function {
                Self::emit_function(b, child, Some(&name), self.name_transform);
                b.blank();
            }
        }
    }
}

impl Emitter for SymbolEmmyDocEmitter {
    fn id(&self) -> &str {
        "symbol-emmydoc"
    }
    fn input_kind(&self) -> &str {
        EMITTER_KIND_SYMBOLS
    }
    fn emit(&self, input: &dyn std::any::Any, meta: &CodegenMeta) -> CodegenResult {
        let Some(symbols) = downcast_symbols(input) else {
            return CodegenResult {
                files: vec![],
                errors: vec!["expected Vec<SymbolDef>".into()],
            };
        };
        let mut b = SourceBuilder::default();
        b.line(format!(
            "-- Generated by Prism Codegen — {}",
            meta.project_name
        ));
        b.line("-- LuaLS type stubs — do not edit manually.");
        b.blank();
        for sym in symbols {
            b.blank();
            self.emit_symbol(&mut b, sym);
        }
        if let Some(table) = &self.return_table {
            b.blank();
            b.line(format!("return {table}"));
        }
        CodegenResult {
            files: vec![EmittedFile {
                filename: self.filename_for(meta),
                content: b.build(),
                language: "luau".into(),
            }],
            errors: vec![],
        }
    }
}

// ── GDScript emitter ───────────────────────────────────────────────

/// GDScript emitter. Tab-indented (Godot convention); uses
/// `class_name` preamble and inner classes for namespaces.
#[derive(Debug, Default, Clone)]
pub struct SymbolGDScriptEmitter {
    pub class_name: Option<String>,
    pub filename: Option<String>,
    pub name_transform: Option<NameTransform>,
}

impl SymbolGDScriptEmitter {
    pub fn new() -> Self {
        Self {
            name_transform: Some(default_gdscript_name_transform),
            ..Self::default()
        }
    }

    pub fn with_class_name(mut self, class_name: impl Into<String>) -> Self {
        self.class_name = Some(class_name.into());
        self
    }

    pub fn with_name_transform(mut self, transform: NameTransform) -> Self {
        self.name_transform = Some(transform);
        self
    }

    fn filename_for(&self, meta: &CodegenMeta) -> String {
        self.filename.clone().unwrap_or_else(|| {
            format!(
                "{}.g.gd",
                self.class_name.as_deref().unwrap_or(&meta.project_name)
            )
        })
    }

    fn gd_type(type_: Option<&str>) -> String {
        match type_ {
            None => "Variant".into(),
            Some("string") => "String".into(),
            Some("number") => "float".into(),
            Some("boolean") => "bool".into(),
            Some("void") => "void".into(),
            Some("int") => "int".into(),
            Some("float") => "float".into(),
            Some(other) => other.to_owned(),
        }
    }

    fn gd_literal(value: &JsonValue) -> String {
        match value {
            JsonValue::String(s) => format!("\"{s}\""),
            JsonValue::Bool(b) => if *b { "true" } else { "false" }.into(),
            JsonValue::Null => "null".into(),
            other => other.to_string(),
        }
    }

    fn gd_comment(b: &mut SourceBuilder, text: Option<&String>) {
        if let Some(t) = text {
            b.line(format!("## {t}"));
        }
    }

    fn emit_symbol(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        match sym.kind {
            SymbolKind::Constant => self.emit_constant(b, sym),
            SymbolKind::Namespace => self.emit_namespace(b, sym),
            SymbolKind::Enum => self.emit_enum(b, sym),
            SymbolKind::Function => self.emit_function(b, sym),
            SymbolKind::Class => self.emit_class(b, sym),
            SymbolKind::Field => self.emit_field(b, sym),
        }
    }

    fn emit_constant(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::gd_comment(b, sym.description.as_ref());
        let val = match sym.value.as_ref() {
            Some(v) => Self::gd_literal(v),
            None => "null".into(),
        };
        b.line(format!("const {name} = {val}"));
    }

    fn emit_namespace(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::gd_comment(b, sym.description.as_ref());
        b.line(format!("class {name}:"));
        b.indent();
        if sym.children.is_empty() {
            b.line("pass");
        } else {
            for child in &sym.children {
                self.emit_symbol(b, child);
            }
        }
        b.dedent();
    }

    fn emit_enum(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::gd_comment(b, sym.description.as_ref());
        if sym.enum_values.is_empty() {
            b.line(format!("enum {name} {{}}"));
        } else {
            let entries = sym
                .enum_values
                .iter()
                .map(|v| {
                    if let JsonValue::Number(n) = &v.value {
                        format!("{} = {n}", v.name)
                    } else {
                        v.name.clone()
                    }
                })
                .collect::<Vec<_>>()
                .join(", ");
            b.line(format!("enum {name} {{ {entries} }}"));
        }
    }

    fn emit_function(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::gd_comment(b, sym.description.as_ref());
        let params = sym
            .params
            .iter()
            .map(|p| {
                let type_ = Self::gd_type(Some(&p.r#type));
                let def = p
                    .default_value
                    .as_ref()
                    .map(|v| format!(" = {}", Self::gd_literal(v)))
                    .unwrap_or_default();
                format!("{}: {type_}{def}", p.name)
            })
            .collect::<Vec<_>>()
            .join(", ");
        let ret = sym
            .returns
            .as_deref()
            .map(|r| format!(" -> {}", Self::gd_type(Some(r))))
            .unwrap_or_default();
        b.line(format!("func {name}({params}){ret}:"));
        b.indent();
        b.line("pass");
        b.dedent();
    }

    fn emit_class(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::gd_comment(b, sym.description.as_ref());
        b.line(format!("class {name}:"));
        b.indent();
        if sym.children.is_empty() {
            b.line("pass");
        } else {
            for child in &sym.children {
                self.emit_symbol(b, child);
            }
        }
        b.dedent();
    }

    fn emit_field(&self, b: &mut SourceBuilder, sym: &SymbolDef) {
        let name = transform(&sym.name, sym.kind, self.name_transform);
        Self::gd_comment(b, sym.description.as_ref());
        let type_ = Self::gd_type(sym.r#type.as_deref());
        b.line(format!("var {name}: {type_}"));
    }
}

impl Emitter for SymbolGDScriptEmitter {
    fn id(&self) -> &str {
        "symbol-gdscript"
    }
    fn input_kind(&self) -> &str {
        EMITTER_KIND_SYMBOLS
    }
    fn emit(&self, input: &dyn std::any::Any, meta: &CodegenMeta) -> CodegenResult {
        let Some(symbols) = downcast_symbols(input) else {
            return CodegenResult {
                files: vec![],
                errors: vec!["expected Vec<SymbolDef>".into()],
            };
        };
        let mut b = SourceBuilder::new("\t");
        b.line(format!(
            "# Generated by Prism Codegen — {}",
            meta.project_name
        ));
        b.line("# Do not edit manually. Re-run the build to regenerate.");
        b.blank();
        let class_name = self.class_name.as_deref().unwrap_or("Generated");
        b.line(format!("class_name {class_name}"));
        for sym in symbols {
            b.blank();
            self.emit_symbol(&mut b, sym);
        }
        CodegenResult {
            files: vec![EmittedFile {
                filename: self.filename_for(meta),
                content: b.build(),
                language: "gdscript".into(),
            }],
            errors: vec![],
        }
    }
}

// ── Default name transforms ────────────────────────────────────────

/// GDScript: constants → SCREAMING_SNAKE, functions/fields → snake_case,
/// classes/namespaces/enums → PascalCase. Applied by
/// [`SymbolGDScriptEmitter::new`] by default.
pub fn default_gdscript_name_transform(name: &str, kind: SymbolKind) -> String {
    match kind {
        SymbolKind::Constant => to_screaming_snake(name),
        SymbolKind::Function | SymbolKind::Field => to_snake_case(name),
        SymbolKind::Namespace | SymbolKind::Class | SymbolKind::Enum => to_pascal_case(name),
    }
}

/// TypeScript: camelCase for constants and fields, PascalCase for
/// everything else (types, functions, namespaces).
pub fn ts_name_transform(name: &str, kind: SymbolKind) -> String {
    match kind {
        SymbolKind::Constant | SymbolKind::Field => to_camel_case(name),
        SymbolKind::Namespace | SymbolKind::Class | SymbolKind::Enum | SymbolKind::Function => {
            to_pascal_case(name)
        }
    }
}

/// C#: PascalCase for every symbol kind.
pub fn cs_name_transform(name: &str, _kind: SymbolKind) -> String {
    to_pascal_case(name)
}

#[cfg(test)]
mod tests {
    use super::super::symbol_def::{constant_namespace, SymbolParam};
    use super::*;
    use serde_json::json;

    fn sample_symbols() -> Vec<SymbolDef> {
        vec![
            constant_namespace(
                "CONVERSATIONS",
                [
                    ("TAVERN_INTRO", "tavern_intro"),
                    ("GUARD_PATROL", "guard_patrol"),
                ],
                Some("Conversation IDs".into()),
            ),
            SymbolDef {
                name: "StartConversation".into(),
                kind: SymbolKind::Function,
                params: vec![
                    SymbolParam::new("id", "string"),
                    SymbolParam::new("actorId", "string").optional(true),
                ],
                returns: Some("void".into()),
                ..SymbolDef::default()
            },
        ]
    }

    #[test]
    fn ts_emitter_emits_export_const_and_declare_function() {
        let emitter = SymbolTypeScriptEmitter::new().with_module_name("Quests");
        let result = emitter.emit(&sample_symbols(), &CodegenMeta::new("Quests"));
        assert_eq!(result.errors, Vec::<String>::new());
        assert_eq!(result.files.len(), 1);
        let f = &result.files[0];
        assert_eq!(f.filename, "Quests.g.ts");
        assert_eq!(f.language, "typescript");
        assert!(f.content.contains("/* eslint-disable */"));
        assert!(f.content.contains("export const CONVERSATIONS = {"));
        assert!(f.content.contains("TAVERN_INTRO: 'tavern_intro',"));
        assert!(f.content.contains(
            "export declare function StartConversation(id: string, actorId?: string): void;"
        ));
    }

    #[test]
    fn csharp_emitter_wraps_in_namespace_block() {
        let emitter = SymbolCSharpEmitter::new()
            .with_namespace("Prism.Quests")
            .with_class_name("Quests");
        let result = emitter.emit(&sample_symbols(), &CodegenMeta::new("Quests"));
        let content = &result.files[0].content;
        assert!(content.contains("namespace Prism.Quests"));
        assert!(content.contains("public static class CONVERSATIONS"));
        assert!(content.contains("public const string TAVERN_INTRO = \"tavern_intro\";"));
        assert!(
            content.contains("public static void StartConversation(string id, string actorId) { }")
        );
    }

    #[test]
    fn emmydoc_emitter_emits_class_and_field_annotations() {
        let emitter = SymbolEmmyDocEmitter::new().with_global_name("Quests");
        let result = emitter.emit(&sample_symbols(), &CodegenMeta::new("Quests"));
        let content = &result.files[0].content;
        assert!(content.contains("---@class CONVERSATIONS"));
        assert!(content.contains("---@field TAVERN_INTRO string"));
        // Top-level functions get qualified by the configured global name.
        assert!(content.contains("function Quests.StartConversation(id, actorId) end"));
    }

    #[test]
    fn gdscript_emitter_uses_tab_indent_and_pascal_snake_case() {
        let emitter = SymbolGDScriptEmitter::new().with_class_name("Quests");
        let result = emitter.emit(&sample_symbols(), &CodegenMeta::new("Quests"));
        let content = &result.files[0].content;
        assert!(content.starts_with("# Generated by Prism Codegen"));
        assert!(content.contains("class_name Quests"));
        // Function name passes through default GDScript transform
        // (snake_case): StartConversation → start_conversation.
        assert!(content.contains("func start_conversation("));
        // Namespaces get PascalCase.
        assert!(content.contains("class Conversations:"));
        // Constant value uses `const NAME = "tavern_intro"` with tab
        // indent inside the inner class.
        assert!(content.contains("\tconst TAVERN_INTRO = \"tavern_intro\""));
    }

    #[test]
    fn enum_ts_emitter_emits_value_object_and_type_alias() {
        let enum_sym = SymbolDef {
            name: "Count".into(),
            kind: SymbolKind::Enum,
            enum_values: vec![
                super::super::symbol_def::EnumValue {
                    name: "One".into(),
                    value: json!("one"),
                    description: None,
                },
                super::super::symbol_def::EnumValue {
                    name: "Two".into(),
                    value: json!("two"),
                    description: None,
                },
            ],
            ..SymbolDef::default()
        };
        let emitter = SymbolTypeScriptEmitter::new().with_module_name("m");
        let result = emitter.emit(&vec![enum_sym], &CodegenMeta::new("m"));
        let content = &result.files[0].content;
        assert!(content.contains("export const Count = {"));
        assert!(content.contains("One: 'one',"));
        assert!(content.contains("export type Count = typeof Count[keyof typeof Count];"));
    }

    #[test]
    fn emit_returns_error_when_input_is_wrong_type() {
        let emitter = SymbolTypeScriptEmitter::new();
        let bogus: String = "not symbols".into();
        let result = emitter.emit(&bogus, &CodegenMeta::new("x"));
        assert!(result.files.is_empty());
        assert_eq!(result.errors, vec!["expected Vec<SymbolDef>".to_string()]);
    }

    #[test]
    fn ts_name_transform_renames_constants_to_camel_case() {
        assert_eq!(
            ts_name_transform("SOME_THING", SymbolKind::Constant),
            "someThing"
        );
        assert_eq!(
            ts_name_transform("some_thing", SymbolKind::Namespace),
            "SomeThing"
        );
    }
}
