import { SourceBuilder } from './source-builder.js';
import type { Emitter, CodegenMeta, CodegenResult } from './codegen-types.js';
import type { SymbolDef, SymbolKind, SymbolParam } from './symbol-def.js';
import { toPascalCase, toCamelCase, toScreamingSnake, toSnakeCase } from '../syntax/case-utils.js';

// -- Name transform ---------------------------------------------------------

/**
 * Optional name transform applied by emitters to symbol names.
 * Allows SymbolDefs to store canonical names while each target language
 * applies its naming convention (camelCase for TS, PascalCase for C#,
 * SCREAMING_SNAKE for GDScript, etc.).
 */
export type NameTransform = (name: string, kind: SymbolKind) => string;

// -- Base class -------------------------------------------------------------

/**
 * SymbolEmitter -- base class for emitters that accept SymbolDef[] as input.
 *
 * Subclasses override the emit* methods for their target language.
 * The base class handles tree traversal (namespace children) and
 * provides helpers for common patterns.
 */
export abstract class SymbolEmitter implements Emitter<SymbolDef[]> {
  abstract readonly id: string;
  readonly inputKind = 'symbols' as const;
  protected abstract readonly language: string;
  protected abstract readonly fileExtension: string;
  protected abstract filename(meta: CodegenMeta): string;

  /** Optional name transform applied to all symbol names during emission. */
  protected nameTransform?: NameTransform;

  emit(symbols: SymbolDef[], meta: CodegenMeta): CodegenResult {
    const b = new SourceBuilder();
    this.emitHeader(b, meta);
    b.blank();
    this.emitPreamble(b, meta);
    for (const sym of symbols) {
      b.blank();
      this.emitSymbol(b, sym, 0);
    }
    this.emitPostamble(b, meta);

    return {
      files: [{ filename: this.filename(meta), content: b.build(), language: this.language }],
      errors: [],
    };
  }

  // -- Override points ------------------------------------------------------

  protected emitHeader(b: SourceBuilder, meta: CodegenMeta): void {
    b.line(`// Generated by Prism Codegen — ${meta.projectName}`);
    b.line('// Do not edit manually. Re-run the build to regenerate.');
  }

  protected emitPreamble(_b: SourceBuilder, _meta: CodegenMeta): void {}
  protected emitPostamble(_b: SourceBuilder, _meta: CodegenMeta): void {}

  protected abstract emitSymbol(b: SourceBuilder, sym: SymbolDef, depth: number): void;

  // -- Shared helpers -------------------------------------------------------

  /** Apply the nameTransform if set, otherwise return name as-is. */
  protected transformName(name: string, kind: SymbolKind): string {
    return this.nameTransform ? this.nameTransform(name, kind) : name;
  }

  protected docComment(b: SourceBuilder, text: string | undefined): void {
    if (text) b.line(`/** ${text} */`);
  }

  protected paramList(params: SymbolParam[] | undefined): string {
    return (params ?? []).map((p) => `${p.name}${p.optional ? '?' : ''}: ${p.type}`).join(', ');
  }
}

// -- TypeScript emitter -----------------------------------------------------

/**
 * SymbolTypeScriptEmitter -- emits TypeScript constants and types from SymbolDef[].
 *
 * Output pattern:
 *   export const CONVERSATIONS = { TAVERN_INTRO: 'tavern_intro' } as const;
 *   export type ConversationId = typeof CONVERSATIONS[keyof typeof CONVERSATIONS];
 *   export declare function StartConversation(id: string, actorId?: string): void;
 */
export class SymbolTypeScriptEmitter extends SymbolEmitter {
  readonly id = 'symbol-typescript';
  protected readonly language = 'typescript';
  protected readonly fileExtension = '.ts';

  constructor(private opts: { moduleName?: string; filename?: string; nameTransform?: NameTransform } = {}) {
    super();
    if (opts.nameTransform !== undefined) this.nameTransform = opts.nameTransform;
  }

  protected filename(meta: CodegenMeta): string {
    return this.opts.filename ?? `${this.opts.moduleName ?? meta.projectName}.g.ts`;
  }

  protected override emitHeader(b: SourceBuilder, meta: CodegenMeta): void {
    b.line(`// Generated by Prism Codegen — ${meta.projectName}`);
    b.line('// Do not edit manually. Re-run the build to regenerate.');
    b.line('/* eslint-disable */');
  }

  protected emitSymbol(b: SourceBuilder, sym: SymbolDef, depth: number): void {
    const indent = depth > 0;

    switch (sym.kind) {
      case 'constant':
        return this._emitConstant(b, sym, indent);
      case 'namespace':
        return this._emitNamespace(b, sym, depth);
      case 'enum':
        return this._emitEnum(b, sym, indent);
      case 'function':
        return this._emitFunction(b, sym, indent);
      case 'class':
        return this._emitClass(b, sym, indent);
      case 'field':
        return this._emitField(b, sym);
    }
  }

  private _emitConstant(b: SourceBuilder, sym: SymbolDef, indent: boolean): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`/** ${sym.description} */`);
    const val = typeof sym.value === 'string' ? `'${sym.value}'` : String(sym.value ?? 'undefined');
    if (indent) {
      b.line(`${name}: ${val},`);
    } else {
      b.line(`export const ${name} = ${val} as const;`);
    }
  }

  private _emitNamespace(b: SourceBuilder, sym: SymbolDef, depth: number): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`/** ${sym.description} */`);
    if (depth === 0) {
      b.line(`export const ${name} = {`);
    } else {
      b.line(`${name}: {`);
    }
    b.indent();
    for (const child of sym.children ?? []) {
      this.emitSymbol(b, child, depth + 1);
    }
    b.dedent();
    b.line(depth === 0 ? '} as const;' : '},');
  }

  private _emitEnum(b: SourceBuilder, sym: SymbolDef, indent: boolean): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`/** ${sym.description} */`);
    b.line(`${indent ? '' : 'export '}const ${name} = {`);
    b.indent();
    for (const v of sym.enumValues ?? []) {
      if (v.description) b.line(`/** ${v.description} */`);
      const val = typeof v.value === 'string' ? `'${v.value}'` : String(v.value);
      b.line(`${v.name}: ${val},`);
    }
    b.dedent();
    b.line('} as const;');
    b.line(`${indent ? '' : 'export '}type ${name} = typeof ${name}[keyof typeof ${name}];`);
  }

  private _emitFunction(b: SourceBuilder, sym: SymbolDef, indent: boolean): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`/** ${sym.description} */`);
    if (sym.deprecated) b.line(`/** @deprecated ${sym.deprecated} */`);
    const params = this.paramList(sym.params);
    const ret = sym.returns ?? 'void';
    const async_ = sym.async ? 'async ' : '';
    b.line(`${indent ? '' : 'export '}declare ${async_}function ${name}(${params}): ${ret};`);
  }

  private _emitClass(b: SourceBuilder, sym: SymbolDef, indent: boolean): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`/** ${sym.description} */`);
    b.line(`${indent ? '' : 'export '}interface ${name} {`);
    b.indent();
    for (const child of sym.children ?? []) {
      this.emitSymbol(b, child, 1);
    }
    b.dedent();
    b.line('}');
  }

  private _emitField(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`/** ${sym.description} */`);
    const opt = sym.type?.endsWith('?') ? '?' : '';
    const type = opt && sym.type ? sym.type.slice(0, -1) : (sym.type ?? 'unknown');
    b.line(`${name}${opt}: ${type};`);
  }
}

// -- C# emitter -------------------------------------------------------------

/**
 * SymbolCSharpEmitter -- emits C# static classes from SymbolDef[].
 *
 * Output pattern:
 *   public static class Conversations {
 *     public const string TavernIntro = "tavern_intro";
 *   }
 */
export class SymbolCSharpEmitter extends SymbolEmitter {
  readonly id = 'symbol-csharp';
  protected readonly language = 'csharp';
  protected readonly fileExtension = '.cs';

  constructor(
    private opts: {
      namespace?: string;
      className?: string;
      filename?: string;
      nameTransform?: NameTransform;
    } = {},
  ) {
    super();
    if (opts.nameTransform !== undefined) this.nameTransform = opts.nameTransform;
  }

  protected filename(meta: CodegenMeta): string {
    return this.opts.filename ?? `${this.opts.className ?? meta.projectName}.g.cs`;
  }

  protected override emitHeader(b: SourceBuilder, meta: CodegenMeta): void {
    b.line(`// Generated by Prism Codegen — ${meta.projectName}`);
    b.line('// Do not edit manually. Re-run the build to regenerate.');
  }

  protected override emitPreamble(b: SourceBuilder, _meta: CodegenMeta): void {
    const ns = this.opts.namespace ?? 'Prism';
    b.line(`namespace ${ns}`);
    b.line('{');
    b.indent();
  }

  protected override emitPostamble(b: SourceBuilder, _meta: CodegenMeta): void {
    b.dedent();
    b.line('}');
  }

  protected emitSymbol(b: SourceBuilder, sym: SymbolDef, _depth: number): void {
    switch (sym.kind) {
      case 'constant': return this._emitConstant(b, sym);
      case 'namespace': return this._emitNamespace(b, sym);
      case 'enum': return this._emitEnum(b, sym);
      case 'function': return this._emitMethod(b, sym);
      case 'class': return this._emitClass(b, sym);
      case 'field': return this._emitField(b, sym);
    }
  }

  private _xmlDoc(b: SourceBuilder, text: string | undefined): void {
    if (text) b.line(`/// <summary>${text}</summary>`);
  }

  private _csType(type: string | undefined): string {
    if (!type) return 'object';
    const map: Record<string, string> = {
      string: 'string', number: 'float', boolean: 'bool', void: 'void',
    };
    return map[type] ?? type;
  }

  private _emitConstant(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._xmlDoc(b, sym.description);
    const type = this._csType(sym.type ?? 'string');
    const val = typeof sym.value === 'string' ? `"${sym.value}"` : String(sym.value ?? 'null');
    b.line(`public const ${type} ${name} = ${val};`);
  }

  private _emitNamespace(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._xmlDoc(b, sym.description);
    b.line(`public static class ${name}`);
    b.line('{');
    b.indent();
    for (const child of sym.children ?? []) {
      this.emitSymbol(b, child, 1);
    }
    b.dedent();
    b.line('}');
  }

  private _emitEnum(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._xmlDoc(b, sym.description);
    b.line(`public enum ${name}`);
    b.line('{');
    b.indent();
    for (const v of sym.enumValues ?? []) {
      if (v.description) b.line(`/// <summary>${v.description}</summary>`);
      b.line(`${v.name},`);
    }
    b.dedent();
    b.line('}');
  }

  private _emitMethod(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._xmlDoc(b, sym.description);
    const params = (sym.params ?? [])
      .map((p) => `${this._csType(p.type)} ${p.name}`)
      .join(', ');
    const ret = this._csType(sym.returns ?? 'void');
    b.line(`public static ${ret} ${name}(${params}) { }`);
  }

  private _emitClass(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._xmlDoc(b, sym.description);
    b.line(`public class ${name}`);
    b.line('{');
    b.indent();
    for (const child of sym.children ?? []) {
      this.emitSymbol(b, child, 1);
    }
    b.dedent();
    b.line('}');
  }

  private _emitField(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._xmlDoc(b, sym.description);
    b.line(`public ${this._csType(sym.type)} ${name};`);
  }
}

// -- Luau EmmyDoc emitter ---------------------------------------------------

/**
 * SymbolEmmyDocEmitter -- emits LuaLS-compatible .d.luau stubs (Luau) from SymbolDef[].
 *
 * Output pattern:
 *   ---@class MyModule
 *   ---@field StartConversation fun(id: string, actorId?: string): void
 *   MyModule = {}
 *
 *   --- Start a conversation by ID.
 *   ---@param id string
 *   ---@param actorId? string
 *   function MyModule.StartConversation(id, actorId) end
 */
export class SymbolEmmyDocEmitter extends SymbolEmitter {
  readonly id = 'symbol-emmydoc';
  protected readonly language = 'luau';
  protected readonly fileExtension = '.d.luau';

  constructor(
    private opts: {
      globalName?: string;
      filename?: string;
      nameTransform?: NameTransform;
      /** If set, emit `return <tableName>` at the end of the file. */
      returnTable?: string;
    } = {},
  ) {
    super();
    if (opts.nameTransform !== undefined) this.nameTransform = opts.nameTransform;
  }

  protected filename(meta: CodegenMeta): string {
    return this.opts.filename ?? `${this.opts.globalName ?? meta.projectName}.d.luau`;
  }

  protected override emitHeader(b: SourceBuilder, meta: CodegenMeta): void {
    b.line(`-- Generated by Prism Codegen — ${meta.projectName}`);
    b.line('-- LuaLS type stubs — do not edit manually.');
  }

  protected override emitPostamble(b: SourceBuilder, _meta: CodegenMeta): void {
    if (this.opts.returnTable) {
      b.blank();
      b.line(`return ${this.opts.returnTable}`);
    }
  }

  protected emitSymbol(b: SourceBuilder, sym: SymbolDef, _depth: number): void {
    const ns = this.opts.globalName;
    switch (sym.kind) {
      case 'constant': return this._emitConstant(b, sym, ns);
      case 'namespace': return this._emitNamespace(b, sym);
      case 'enum': return this._emitEnum(b, sym);
      case 'function': return this._emitFunction(b, sym, ns);
      case 'class': return this._emitClass(b, sym);
      case 'field': break; // fields handled inside namespace/class
    }
  }

  private _emitConstant(b: SourceBuilder, sym: SymbolDef, ns: string | undefined): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`--- ${sym.description}`);
    b.line(`---@type ${sym.type ?? 'unknown'}`);
    const qual = ns ? `${ns}.` : '';
    b.line(`${qual}${name} = nil`);
  }

  private _emitNamespace(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`--- ${sym.description}`);
    b.line(`---@class ${name}`);
    // Emit @field for each child
    for (const child of sym.children ?? []) {
      const childName = this.transformName(child.name, child.kind);
      const typeStr = this._fieldType(child);
      const desc = child.description ? ` # ${child.description}` : '';
      b.line(`---@field ${childName} ${typeStr}${desc}`);
    }
    b.line(`${name} = {}`);
    b.blank();
    // Emit full function signatures for child functions
    for (const child of sym.children ?? []) {
      if (child.kind === 'function') {
        this._emitFunction(b, child, name);
        b.blank();
      }
    }
    // Recursively emit child namespaces, enums, and classes as their own blocks
    for (const child of sym.children ?? []) {
      if (child.kind === 'namespace' || child.kind === 'class' || child.kind === 'enum') {
        this.emitSymbol(b, child, 1);
        b.blank();
      }
    }
  }

  private _emitEnum(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`--- ${sym.description}`);
    b.line(`---@alias ${name}`);
    for (const v of sym.enumValues ?? []) {
      const val = typeof v.value === 'string' ? `"${v.value}"` : String(v.value);
      b.line(`---| ${val} # ${v.name}${v.description ? ` — ${v.description}` : ''}`);
    }
    b.line('');
  }

  private _emitFunction(b: SourceBuilder, sym: SymbolDef, ns: string | undefined): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`--- ${sym.description}`);
    if (sym.deprecated) b.line(`---@deprecated ${sym.deprecated}`);
    for (const p of sym.params ?? []) {
      b.line(`---@param ${p.name}${p.optional ? '?' : ''} ${p.type}${p.description ? ` # ${p.description}` : ''}`);
    }
    if (sym.returns) b.line(`---@return ${sym.returns}`);
    const params = (sym.params ?? []).map((p) => p.name).join(', ');
    const qual = ns ? `${ns}.` : '';
    b.line(`function ${qual}${name}(${params}) end`);
  }

  private _emitClass(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    if (sym.description) b.line(`--- ${sym.description}`);
    b.line(`---@class ${name}`);
    for (const child of sym.children ?? []) {
      if (child.kind === 'field') {
        const childName = this.transformName(child.name, child.kind);
        const desc = child.description ? ` # ${child.description}` : '';
        b.line(`---@field ${childName} ${child.type ?? 'unknown'}${desc}`);
      }
    }
    b.line(`local ${name} = {}`);
    b.blank();
    for (const child of sym.children ?? []) {
      if (child.kind === 'function') {
        this._emitFunction(b, child, name);
        b.blank();
      }
    }
  }

  private _fieldType(sym: SymbolDef): string {
    if (sym.kind === 'function') {
      const params = (sym.params ?? []).map((p) => `${p.name}: ${p.type}`).join(', ');
      return `fun(${params})${sym.returns ? `: ${sym.returns}` : ''}`;
    }
    if (sym.kind === 'constant') return sym.type ?? 'unknown';
    if (sym.kind === 'namespace' || sym.kind === 'class') return sym.name;
    return 'unknown';
  }
}

// -- GDScript emitter -------------------------------------------------------

/**
 * SymbolGDScriptEmitter -- emits GDScript constants and classes from SymbolDef[].
 *
 * Godot conventions:
 *   - Tab-indented (GDScript standard)
 *   - class_name at top
 *   - Inner classes for namespaces
 *   - SCREAMING_SNAKE_CASE for constants
 *   - snake_case for functions/variables
 *   - PascalCase for classes/enums
 *   - Empty classes get `pass`
 */
export class SymbolGDScriptEmitter extends SymbolEmitter {
  readonly id = 'symbol-gdscript';
  protected readonly language = 'gdscript';
  protected readonly fileExtension = '.gd';

  constructor(
    private opts: {
      className?: string;
      filename?: string;
      nameTransform?: NameTransform;
    } = {},
  ) {
    super();
    this.nameTransform = opts.nameTransform ?? defaultGDScriptNameTransform;
  }

  protected filename(meta: CodegenMeta): string {
    return this.opts.filename ?? `${this.opts.className ?? meta.projectName}.g.gd`;
  }

  protected override emitHeader(b: SourceBuilder, meta: CodegenMeta): void {
    b.line(`# Generated by Prism Codegen — ${meta.projectName}`);
    b.line('# Do not edit manually. Re-run the build to regenerate.');
  }

  protected override emitPreamble(b: SourceBuilder, _meta: CodegenMeta): void {
    const className = this.opts.className ?? 'Generated';
    b.line(`class_name ${className}`);
  }

  override emit(symbols: SymbolDef[], meta: CodegenMeta): CodegenResult {
    // GDScript uses tabs, not spaces
    const b = new SourceBuilder('\t');
    this.emitHeader(b, meta);
    b.blank();
    this.emitPreamble(b, meta);
    for (const sym of symbols) {
      b.blank();
      this.emitSymbol(b, sym, 0);
    }
    this.emitPostamble(b, meta);

    return {
      files: [{ filename: this.filename(meta), content: b.build(), language: this.language }],
      errors: [],
    };
  }

  protected emitSymbol(b: SourceBuilder, sym: SymbolDef, depth: number): void {
    switch (sym.kind) {
      case 'constant': return this._emitConstant(b, sym);
      case 'namespace': return this._emitNamespace(b, sym, depth);
      case 'enum': return this._emitEnum(b, sym);
      case 'function': return this._emitFunction(b, sym);
      case 'class': return this._emitClass(b, sym, depth);
      case 'field': return this._emitField(b, sym);
    }
  }

  private _gdType(type: string | undefined): string {
    if (!type) return 'Variant';
    const map: Record<string, string> = {
      string: 'String', number: 'float', boolean: 'bool', void: 'void',
      int: 'int', float: 'float',
    };
    return map[type] ?? type;
  }

  private _gdComment(b: SourceBuilder, text: string | undefined): void {
    if (text) b.line(`## ${text}`);
  }

  private _emitConstant(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._gdComment(b, sym.description);
    const val = typeof sym.value === 'string' ? `"${sym.value}"` : String(sym.value ?? 'null');
    b.line(`const ${name} = ${val}`);
  }

  private _emitNamespace(b: SourceBuilder, sym: SymbolDef, depth: number): void {
    const name = this.transformName(sym.name, sym.kind);
    this._gdComment(b, sym.description);
    b.line(`class ${name}:`);
    b.indent();
    const children = sym.children ?? [];
    if (children.length === 0) {
      b.line('pass');
    } else {
      for (const child of children) {
        this.emitSymbol(b, child, depth + 1);
      }
    }
    b.dedent();
  }

  private _emitEnum(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._gdComment(b, sym.description);
    const values = sym.enumValues ?? [];
    if (values.length === 0) {
      b.line(`enum ${name} {}`);
    } else {
      const entries = values.map((v) => {
        if (typeof v.value === 'number') return `${v.name} = ${v.value}`;
        return v.name;
      });
      b.line(`enum ${name} { ${entries.join(', ')} }`);
    }
  }

  private _emitFunction(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._gdComment(b, sym.description);
    const params = (sym.params ?? [])
      .map((p) => {
        const type = this._gdType(p.type);
        const def = p.defaultValue !== undefined ? ` = ${this._gdLiteral(p.defaultValue)}` : '';
        return `${p.name}: ${type}${def}`;
      })
      .join(', ');
    const ret = sym.returns ? ` -> ${this._gdType(sym.returns)}` : '';
    b.line(`func ${name}(${params})${ret}:`);
    b.indent();
    b.line('pass');
    b.dedent();
  }

  private _emitClass(b: SourceBuilder, sym: SymbolDef, depth: number): void {
    const name = this.transformName(sym.name, sym.kind);
    this._gdComment(b, sym.description);
    b.line(`class ${name}:`);
    b.indent();
    const children = sym.children ?? [];
    if (children.length === 0) {
      b.line('pass');
    } else {
      for (const child of children) {
        this.emitSymbol(b, child, depth + 1);
      }
    }
    b.dedent();
  }

  private _emitField(b: SourceBuilder, sym: SymbolDef): void {
    const name = this.transformName(sym.name, sym.kind);
    this._gdComment(b, sym.description);
    const type = this._gdType(sym.type);
    b.line(`var ${name}: ${type}`);
  }

  private _gdLiteral(value: unknown): string {
    if (typeof value === 'string') return `"${value}"`;
    if (typeof value === 'boolean') return value ? 'true' : 'false';
    if (value === null || value === undefined) return 'null';
    return String(value);
  }
}

// -- Default name transforms ------------------------------------------------

/** GDScript: constants -> SCREAMING_SNAKE, classes/namespaces -> PascalCase, functions -> snake_case */
function defaultGDScriptNameTransform(name: string, kind: SymbolKind): string {
  switch (kind) {
    case 'constant':
      return toScreamingSnake(name);
    case 'function':
    case 'field':
      return toSnakeCase(name);
    case 'namespace':
    case 'class':
    case 'enum':
      return toPascalCase(name);
  }
}

/** TypeScript: camelCase for constants/fields, PascalCase for types */
export function tsNameTransform(name: string, kind: SymbolKind): string {
  switch (kind) {
    case 'constant':
    case 'field':
      return toCamelCase(name);
    case 'namespace':
    case 'class':
    case 'enum':
    case 'function':
      return toPascalCase(name);
  }
}

/** C#: PascalCase for everything */
export function csNameTransform(name: string, _kind: SymbolKind): string {
  return toPascalCase(name);
}
