//! Hand-maintained registry of every type in `prism-builder` that has
//! been annotated with `#[luau_expose]`. The codegen subcommand
//! (`prism codegen luau-types`) walks this slice to produce
//! `<workspace>/types/builder.d.luau` — the prism-builder fan-out
//! called for in `docs/dev/luau-integration-plan.md` §Phase 5.
//!
//! Same shape as `prism_core::luau_types::type_defs()`: hand-list
//! over `inventory!`-style link-time collection, because cdylib +
//! WASM targets don't reliably surface distributed slices.

use crate::layout::{
    AlignOption, Dimension, FlexDirection, FlowDisplay, GridPlacement, JustifyOption,
};
use crate::style::StyleProperties;

/// Every Luau-exposed type defined in `prism-builder`. Each entry is
/// `(luau type name, full `export type` declaration)`. Curated leaf-first
/// so referenced types declare before their dependents.
pub fn type_defs() -> Vec<(&'static str, &'static str)> {
    prism_core::luau_types![
        // layout leaves
        FlowDisplay,
        FlexDirection,
        AlignOption,
        JustifyOption,
        Dimension,
        GridPlacement,
        // style cascade
        StyleProperties,
    ]
}

/// Concatenate every entry from [`type_defs`] into a single Luau source
/// file, prefixed with `--!strict`. Mirrors `prism_core::luau_types::render_type_stubs`.
pub fn render_type_stubs() -> String {
    let mut out = String::from(
        "--!strict\n-- Generated by `prism codegen luau-types`. Do not edit by hand.\n\n",
    );
    for (_, def) in type_defs() {
        out.push_str(def);
        out.push_str("\n\n");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_includes_layout_and_style_leaves() {
        let names: Vec<&str> = type_defs().iter().map(|(n, _)| *n).collect();
        for expected in [
            "FlowDisplay",
            "FlexDirection",
            "AlignOption",
            "JustifyOption",
            "Dimension",
            "GridPlacement",
            "StyleProperties",
        ] {
            assert!(
                names.contains(&expected),
                "missing {expected} from prism-builder luau type registry"
            );
        }
    }

    #[test]
    fn flow_display_is_string_union() {
        assert_eq!(
            FlowDisplay::LUAU_TYPE_DEF,
            "export type FlowDisplay = \"Block\" | \"Flex\" | \"Grid\" | \"None\""
        );
    }

    #[test]
    fn dimension_is_tagged_union() {
        let def = Dimension::LUAU_TYPE_DEF;
        assert!(def.starts_with("export type Dimension ="));
        assert!(def.contains("{ tag: \"Auto\" }"));
        assert!(def.contains("{ tag: \"Px\", value: number }"));
        assert!(def.contains("{ tag: \"Percent\", value: number }"));
    }

    #[test]
    fn grid_placement_is_tagged_union() {
        let def = GridPlacement::LUAU_TYPE_DEF;
        assert!(def.contains("{ tag: \"Auto\" }"));
        assert!(def.contains("{ tag: \"Line\", index: number }"));
        assert!(def.contains("{ tag: \"Span\", count: number }"));
    }

    #[test]
    fn style_properties_uses_optional_field_syntax() {
        let def = StyleProperties::LUAU_TYPE_DEF;
        assert!(def.contains("font_family: string?"));
        assert!(def.contains("font_size: number?"));
        assert!(def.contains("border_radius: number?"));
    }

    #[cfg(feature = "luau")]
    #[test]
    fn dimension_round_trips_through_lua_table() {
        use mlua::Lua;
        let lua = Lua::new();
        // IntoLua: Rust → Lua table
        lua.globals()
            .set("d", Dimension::Px { value: 12.5 })
            .unwrap();
        let tag: String = lua.load("return d.tag").eval().unwrap();
        let value: f32 = lua.load("return d.value").eval().unwrap();
        assert_eq!(tag, "Px");
        assert_eq!(value, 12.5);
        // FromLua: Lua table → Rust
        let back: Dimension = lua
            .load("return { tag = 'Percent', value = 50 }")
            .eval()
            .unwrap();
        assert_eq!(back, Dimension::Percent { value: 50.0 });
        // Unit variant
        let auto: Dimension = lua.load("return { tag = 'Auto' }").eval().unwrap();
        assert_eq!(auto, Dimension::Auto);
    }

    #[cfg(feature = "luau")]
    #[test]
    fn dimension_unknown_tag_errors() {
        use mlua::Lua;
        let lua = Lua::new();
        let err: Result<Dimension, _> = lua.load("return { tag = 'Bogus' }").eval();
        let msg = format!("{}", err.unwrap_err());
        assert!(msg.contains("Bogus"), "unexpected error: {msg}");
    }

    #[test]
    fn render_type_stubs_emits_strict_header_and_every_def() {
        let rendered = render_type_stubs();
        assert!(rendered.starts_with("--!strict\n"));
        for (_, def) in type_defs() {
            assert!(rendered.contains(def), "stub missing: {def}");
        }
    }
}
