//! Document-level render entry points.
//!
//! Walks a [`BuilderDocument`] against a [`ComponentRegistry`] and
//! produces a rendered output for a given target backend. Two walkers
//! ship today:
//!
//! * [`render_document_html`] — Sovereign Portal SSR path. `prism-relay`
//!   calls this per request.
//! * [`render_document_slint_source`] — Studio builder path. Emits a
//!   self-contained `.slint` source string that declares a single
//!   `BuilderRoot` component wrapping the walked tree. The shell
//!   hands that source to [`slint_interpreter::Compiler`] via
//!   [`compile_slint_source`] / [`instantiate_document`] (enabled
//!   behind the `interpreter` crate feature so host crates that only
//!   want the DSL text don't pay the compiler's dep weight).

use prism_core::design_tokens::DesignTokens;

use crate::component::{RenderError, RenderHtmlContext, RenderSlintContext};
use crate::document::BuilderDocument;
use crate::html::Html;
use crate::registry::ComponentRegistry;
use crate::slint_source::{rgba_to_slint_literal, SlintEmitter};

/// Render a document to an HTML fragment. Emits the root node's
/// markup and every descendant in order. Zones are ignored for now
/// — the portal layer wraps the returned fragment in its own
/// chrome (doctype, `<head>`, OpenGraph meta, etc.).
///
/// Returns a bare fragment string on success. The caller is free to
/// embed it in a full document or stream it through additional
/// transforms.
pub fn render_document_html(
    doc: &BuilderDocument,
    registry: &ComponentRegistry,
    tokens: &DesignTokens,
) -> Result<String, RenderError> {
    let ctx = RenderHtmlContext { tokens, registry };
    let mut out = Html::with_capacity(512);
    if let Some(root) = &doc.root {
        ctx.render_child(root, &mut out)?;
    }
    Ok(out.into_string())
}

/// Render a document to a self-contained `.slint` source string.
///
/// The output declares one top-level `export component BuilderRoot
/// inherits Window { … }` whose body is composed from every
/// registered [`crate::component::Component::render_slint`] impl the
/// walker touches along the way. Empty documents emit a safe empty
/// Window so the Slint compiler always has something to chew on.
///
/// The result is plain text — call [`compile_slint_source`] to hand
/// it to [`slint_interpreter::Compiler`] when the `interpreter`
/// feature is on.
pub fn render_document_slint_source(
    doc: &BuilderDocument,
    registry: &ComponentRegistry,
    tokens: &DesignTokens,
) -> Result<String, RenderError> {
    let ctx = RenderSlintContext { tokens, registry };
    let mut out = SlintEmitter::new();
    out.line("// Auto-generated by prism_builder::render_document_slint_source.");
    out.line("// Do not edit by hand — re-emit the source instead.");
    out.blank();
    out.block("export component BuilderRoot inherits Window", |out| {
        out.prop_px("preferred-width", 1280.0);
        out.prop_px("preferred-height", 800.0);
        out.prop_color(
            "background",
            rgba_to_slint_literal(tokens.colors.background),
        );
        out.blank();
        if let Some(root) = &doc.root {
            out.block("VerticalLayout", |out| {
                out.prop_px("padding", tokens.spacing.lg as f64);
                out.prop_px("spacing", tokens.spacing.md as f64);
                out.line("alignment: start;");
                ctx.render_child(root, out)
            })
        } else {
            out.block("Text", |out| {
                out.prop_string("text", "(empty document)");
                out.prop_color("color", rgba_to_slint_literal(tokens.colors.text_secondary));
                Ok(())
            })
        }
    })?;
    Ok(out.build())
}

/// Error returned when the `slint-interpreter` round-trip fails.
///
/// Only produced by [`compile_slint_source`] / [`instantiate_document`]
/// — the pure [`render_document_slint_source`] path never returns this
/// variant since it never touches the compiler.
#[cfg(feature = "interpreter")]
#[derive(Debug, thiserror::Error)]
pub enum InstantiateError {
    #[error("render failed: {0}")]
    Render(#[from] RenderError),
    #[error("compile failed: {0}")]
    Compile(String),
    #[error("platform error: {0}")]
    Platform(#[from] slint::PlatformError),
}

/// Compile a `.slint` source string through [`slint_interpreter::Compiler`]
/// and return the `BuilderRoot` component definition.
///
/// The compile itself is `async` but in practice synchronous as long
/// as the caller doesn't install a file loader. We poll the future
/// with [`spin_on::spin_on`] to keep the API blocking.
#[cfg(feature = "interpreter")]
pub fn compile_slint_source(
    source: &str,
) -> Result<slint_interpreter::ComponentDefinition, InstantiateError> {
    let compiler = slint_interpreter::Compiler::default();
    let result =
        spin_on::spin_on(compiler.build_from_source(source.to_string(), std::path::PathBuf::new()));
    if result.has_errors() {
        let diags: Vec<String> = result.diagnostics().map(|d| d.to_string()).collect();
        return Err(InstantiateError::Compile(diags.join("\n")));
    }
    result
        .component("BuilderRoot")
        .ok_or_else(|| InstantiateError::Compile("missing BuilderRoot export".into()))
}

/// End-to-end: walk the document, compile the emitted source, and
/// hand back a live [`slint_interpreter::ComponentInstance`]. The
/// Studio shell calls this from its builder panel and plugs the
/// returned instance into a Slint `ComponentContainer` slot.
#[cfg(feature = "interpreter")]
pub fn instantiate_document(
    doc: &BuilderDocument,
    registry: &ComponentRegistry,
    tokens: &DesignTokens,
) -> Result<slint_interpreter::ComponentInstance, InstantiateError> {
    let source = render_document_slint_source(doc, registry, tokens)?;
    let definition = compile_slint_source(&source)?;
    let instance = definition.create()?;
    Ok(instance)
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use serde_json::{json, Value};

    use super::*;
    use crate::component::{Component, ComponentId, RenderHtmlContext, RenderSlintContext};
    use crate::document::Node;
    use crate::registry::FieldSpec;

    /// Tiny `h1`-rendering component used by the walker tests. Reads
    /// its label from `props.text`.
    struct Heading {
        id: ComponentId,
    }

    impl Component for Heading {
        fn id(&self) -> &ComponentId {
            &self.id
        }

        fn schema(&self) -> Vec<FieldSpec> {
            vec![FieldSpec::text("text", "Text")]
        }

        fn render_html(
            &self,
            _ctx: &RenderHtmlContext<'_>,
            props: &Value,
            _children: &[Node],
            out: &mut Html,
        ) -> Result<(), RenderError> {
            let text = props.get("text").and_then(|v| v.as_str()).unwrap_or("");
            out.open("h1");
            out.text(text);
            out.close("h1");
            Ok(())
        }

        fn render_slint(
            &self,
            _ctx: &RenderSlintContext<'_>,
            props: &Value,
            _children: &[Node],
            out: &mut SlintEmitter,
        ) -> Result<(), RenderError> {
            let text = props.get("text").and_then(|v| v.as_str()).unwrap_or("");
            out.block("Text", |out| {
                out.prop_string("text", text);
                out.prop_px("font-size", 24.0);
                Ok(())
            })
        }
    }

    /// Container component used to verify child recursion.
    struct Section {
        id: ComponentId,
    }

    impl Component for Section {
        fn id(&self) -> &ComponentId {
            &self.id
        }

        fn schema(&self) -> Vec<FieldSpec> {
            vec![]
        }

        fn render_html(
            &self,
            ctx: &RenderHtmlContext<'_>,
            _props: &Value,
            children: &[Node],
            out: &mut Html,
        ) -> Result<(), RenderError> {
            out.open("section");
            ctx.render_children(children, out)?;
            out.close("section");
            Ok(())
        }

        fn render_slint(
            &self,
            ctx: &RenderSlintContext<'_>,
            _props: &Value,
            children: &[Node],
            out: &mut SlintEmitter,
        ) -> Result<(), RenderError> {
            out.block("VerticalLayout", |out| {
                out.prop_px("spacing", 12.0);
                ctx.render_children(children, out)
            })
        }
    }

    fn registry_with_samples() -> ComponentRegistry {
        let mut reg = ComponentRegistry::new();
        reg.register(Arc::new(Heading {
            id: "heading".into(),
        }))
        .unwrap();
        reg.register(Arc::new(Section {
            id: "section".into(),
        }))
        .unwrap();
        reg
    }

    #[test]
    fn renders_empty_document_to_empty_string() {
        let doc = BuilderDocument::default();
        let registry = ComponentRegistry::new();
        let tokens = DesignTokens::default();
        let html = render_document_html(&doc, &registry, &tokens).unwrap();
        assert_eq!(html, "");
    }

    #[test]
    fn renders_single_heading() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "Hello Prism" }),
                children: vec![],
            }),
            zones: Default::default(),
        };
        let registry = registry_with_samples();
        let tokens = DesignTokens::default();
        let html = render_document_html(&doc, &registry, &tokens).unwrap();
        assert_eq!(html, "<h1>Hello Prism</h1>");
    }

    #[test]
    fn escapes_user_supplied_text() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "<script>alert('xss')</script>" }),
                children: vec![],
            }),
            zones: Default::default(),
        };
        let registry = registry_with_samples();
        let tokens = DesignTokens::default();
        let html = render_document_html(&doc, &registry, &tokens).unwrap();
        assert_eq!(
            html,
            "<h1>&lt;script&gt;alert(&#39;xss&#39;)&lt;/script&gt;</h1>"
        );
    }

    #[test]
    fn recursive_children_walk() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![
                    Node {
                        id: "n2".into(),
                        component: "heading".into(),
                        props: json!({ "text": "A" }),
                        children: vec![],
                    },
                    Node {
                        id: "n3".into(),
                        component: "heading".into(),
                        props: json!({ "text": "B" }),
                        children: vec![],
                    },
                ],
            }),
            zones: Default::default(),
        };
        let registry = registry_with_samples();
        let tokens = DesignTokens::default();
        let html = render_document_html(&doc, &registry, &tokens).unwrap();
        assert_eq!(html, "<section><h1>A</h1><h1>B</h1></section>");
    }

    #[test]
    fn unknown_component_errors() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "not-registered".into(),
                props: json!({}),
                children: vec![],
            }),
            zones: Default::default(),
        };
        let registry = registry_with_samples();
        let tokens = DesignTokens::default();
        let err = render_document_html(&doc, &registry, &tokens).unwrap_err();
        assert!(matches!(err, RenderError::UnknownComponent(ref id) if id == "not-registered"));
    }

    #[test]
    fn default_html_impl_emits_div_wrapper() {
        struct Plain {
            id: ComponentId,
        }
        impl Component for Plain {
            fn id(&self) -> &ComponentId {
                &self.id
            }
            fn schema(&self) -> Vec<FieldSpec> {
                vec![]
            }
        }

        let mut reg = ComponentRegistry::new();
        reg.register(Arc::new(Plain { id: "plain".into() }))
            .unwrap();
        reg.register(Arc::new(Heading {
            id: "heading".into(),
        }))
        .unwrap();

        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "plain".into(),
                props: json!({}),
                children: vec![Node {
                    id: "n2".into(),
                    component: "heading".into(),
                    props: json!({ "text": "Inside" }),
                    children: vec![],
                }],
            }),
            zones: Default::default(),
        };
        let tokens = DesignTokens::default();
        let html = render_document_html(&doc, &reg, &tokens).unwrap();
        assert_eq!(html, r#"<div data-component="plain"><h1>Inside</h1></div>"#);
    }

    #[test]
    fn slint_source_wraps_body_in_builder_root() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "Hi" }),
                children: vec![],
            }),
            zones: Default::default(),
        };
        let reg = registry_with_samples();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains("export component BuilderRoot inherits Window"));
        assert!(source.contains("preferred-width: 1280px;"));
        assert!(source.contains("Text {"));
        assert!(source.contains(r#"text: "Hi";"#));
    }

    #[test]
    fn slint_source_renders_section_children() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![
                    Node {
                        id: "n2".into(),
                        component: "heading".into(),
                        props: json!({ "text": "A" }),
                        children: vec![],
                    },
                    Node {
                        id: "n3".into(),
                        component: "heading".into(),
                        props: json!({ "text": "B" }),
                        children: vec![],
                    },
                ],
            }),
            zones: Default::default(),
        };
        let reg = registry_with_samples();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains("VerticalLayout {"));
        // Two headings emitted under the section.
        assert_eq!(source.matches(r#"text: "A";"#).count(), 1);
        assert_eq!(source.matches(r#"text: "B";"#).count(), 1);
    }

    #[test]
    fn slint_source_empty_document_emits_placeholder() {
        let doc = BuilderDocument::default();
        let reg = ComponentRegistry::new();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains(r#"text: "(empty document)";"#));
    }

    #[test]
    fn slint_source_escapes_dsl_hostile_text() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "\"oops\"\nsecond" }),
                children: vec![],
            }),
            zones: Default::default(),
        };
        let reg = registry_with_samples();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains(r#"text: "\"oops\"\nsecond";"#));
    }

    #[test]
    fn slint_source_unknown_component_errors() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "missing".into(),
                props: json!({}),
                children: vec![],
            }),
            zones: Default::default(),
        };
        let reg = registry_with_samples();
        let tokens = DesignTokens::default();
        let err = render_document_slint_source(&doc, &reg, &tokens).unwrap_err();
        assert!(matches!(err, RenderError::UnknownComponent(ref id) if id == "missing"));
    }

    #[cfg(feature = "interpreter")]
    #[test]
    fn compile_trivial_slint_source_round_trips() {
        // Verify the interpreter dep is wired up and the synthesized
        // source from the walker is syntactically acceptable. We don't
        // instantiate here — that would require a Slint platform
        // backend we can't guarantee under `cargo test`.
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "Interpreter OK" }),
                children: vec![],
            }),
            zones: Default::default(),
        };
        let reg = registry_with_samples();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        // `compile_slint_source` returns a ComponentDefinition on success.
        let _def = compile_slint_source(&source).expect("walker source should compile");
    }
}
