//! Document-level render entry points.
//!
//! Walks a [`BuilderDocument`] against a [`ComponentRegistry`] and
//! produces a `.slint` source string for the Studio builder. SSR has
//! moved off this module — `prism-relay` calls
//! [`crate::ui_runtime::lower_semantic_html_with_registry`] against
//! the same `BuilderDocument` for HTML output.

use prism_core::design_tokens::DesignTokens;

use crate::component::{RenderError, RenderSlintContext};
use crate::document::BuilderDocument;
use crate::layout::{GridCell, SplitDirection};
use crate::registry::ComponentRegistry;
use crate::slint_source::{rgba_to_slint_literal, SlintEmitter};
use crate::source_map::{PropSpan, SourceMap, SourceSpan};

/// Render a document to a self-contained `.slint` source string.
///
/// The output declares one top-level `export component BuilderRoot
/// inherits Window { … }` whose body is composed from every
/// registered [`crate::component::Component::render_slint`] impl the
/// walker touches along the way. Empty documents emit a safe empty
/// Window so the Slint compiler always has something to chew on.
///
/// The result is plain text — call [`compile_slint_source`] to hand
/// it to [`slint_interpreter::Compiler`] when the `interpreter`
/// feature is on.
pub fn render_document_slint_source(
    doc: &BuilderDocument,
    registry: &ComponentRegistry,
    tokens: &DesignTokens,
) -> Result<String, RenderError> {
    let ctx = RenderSlintContext::new(
        tokens,
        registry,
        &doc.resources,
        &doc.prefabs,
        &doc.facets,
        &doc.facet_schemas,
        false,
    );
    let mut out = SlintEmitter::new();
    out.line("// Auto-generated by prism_builder::render_document_slint_source.");
    out.line("// Do not edit by hand — re-emit the source instead.");
    out.blank();
    out.block("export component BuilderRoot inherits Window", |out| {
        out.prop_px("preferred-width", 1280.0);
        out.prop_px("preferred-height", 800.0);
        out.prop_color(
            "background",
            rgba_to_slint_literal(tokens.colors.background),
        );
        out.blank();
        if let Some(root) = &doc.root {
            out.block("VerticalLayout", |out| {
                out.prop_px("padding", tokens.spacing.lg as f64);
                out.prop_px("spacing", tokens.spacing.md as f64);
                out.line("alignment: start;");
                ctx.render_child(root, out)
            })
        } else {
            out.block("Text", |out| {
                out.prop_string("text", "(empty document)");
                out.prop_color("color", rgba_to_slint_literal(tokens.colors.text_secondary));
                Ok(())
            })
        }
    })?;
    Ok(out.build())
}

/// Render a document to `.slint` source with a [`SourceMap`] that
/// tracks byte ranges for each node (ADR-006).
///
/// Uses the same component walk as [`render_document_slint_source`]
/// but injects `// @node-start:<id>:<component>` / `// @node-end:<id>`
/// marker comments around each node block. The markers are then parsed
/// to build the source map. The markers are present in the source —
/// they're valid Slint comments and don't affect compilation.
/// Render a document to `.slint` source with a [`SourceMap`] that
/// tracks byte ranges for each node (ADR-006).
///
/// Uses the same component walk as [`render_document_slint_source`]
/// but sets `emit_markers = true` on the render context, injecting
/// `// @node-start:<id>:<component>` / `// @node-end:<id>` comments
/// around each node block. These are valid Slint comments and don't
/// affect compilation. The markers are parsed after rendering to
/// build the source map.
pub fn render_document_slint_source_mapped(
    doc: &BuilderDocument,
    registry: &ComponentRegistry,
    tokens: &DesignTokens,
) -> Result<(String, SourceMap), RenderError> {
    let ctx = RenderSlintContext::new(
        tokens,
        registry,
        &doc.resources,
        &doc.prefabs,
        &doc.facets,
        &doc.facet_schemas,
        true,
    );
    let mut out = SlintEmitter::new();
    out.line("// Auto-generated by prism_builder — live bidirectional source (ADR-006).");
    out.blank();
    out.block("export component BuilderRoot inherits Window", |out| {
        out.prop_px("preferred-width", 1280.0);
        out.prop_px("preferred-height", 800.0);
        out.prop_color(
            "background",
            rgba_to_slint_literal(tokens.colors.background),
        );
        out.blank();
        if let Some(root) = &doc.root {
            out.block("VerticalLayout", |out| {
                out.prop_px("padding", tokens.spacing.lg as f64);
                out.prop_px("spacing", tokens.spacing.md as f64);
                out.line("alignment: start;");
                ctx.render_child(root, out)
            })
        } else {
            out.block("Text", |out| {
                out.prop_string("text", "(empty document)");
                out.prop_color("color", rgba_to_slint_literal(tokens.colors.text_secondary));
                Ok(())
            })
        }
    })?;

    let source = out.build();
    let map = build_source_map_from_markers(&source);
    Ok((source, map))
}

pub fn build_source_map_from_markers(source: &str) -> SourceMap {
    let mut map = SourceMap::new();
    let mut pending: Vec<(String, String, usize)> = Vec::new();

    for (line_start, line) in line_byte_offsets(source) {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("// @node-start:") {
            let parts: Vec<&str> = rest.splitn(2, ':').collect();
            if parts.len() == 2 {
                pending.push((parts[0].to_string(), parts[1].to_string(), line_start));
            }
        } else if let Some(rest) = trimmed.strip_prefix("// @node-end:") {
            let node_id = rest.trim();
            let line_end = line_start + line.len();
            if let Some(idx) = pending.iter().rposition(|(id, _, _)| id == node_id) {
                let (id, component, start) = pending.remove(idx);
                let props = extract_prop_spans(source, start, line_end);
                map.insert(SourceSpan {
                    node_id: id,
                    component,
                    start,
                    end: line_end,
                    props,
                });
            }
        }
    }
    map
}

/// Extract property spans from a node's source region, skipping child
/// nodes (identified by nested `@node-start`/`@node-end` markers).
fn extract_prop_spans(source: &str, node_start: usize, node_end: usize) -> Vec<PropSpan> {
    let mut props = Vec::new();
    let mut child_depth: usize = 0;
    let mut seen_own_start = false;
    let clamped_end = node_end.min(source.len());

    for (line_start, line) in line_byte_offsets(source) {
        if line_start >= clamped_end {
            break;
        }
        if line_start + line.len() <= node_start {
            continue;
        }

        let trimmed = line.trim();

        if trimmed.starts_with("// @node-start:") {
            if !seen_own_start {
                seen_own_start = true;
            } else {
                child_depth += 1;
            }
            continue;
        }
        if trimmed.starts_with("// @node-end:") {
            child_depth = child_depth.saturating_sub(1);
            continue;
        }

        if child_depth > 0 {
            continue;
        }

        // Skip comments, block openers, block closers, empty lines.
        if trimmed.is_empty()
            || trimmed.starts_with("//")
            || trimmed.ends_with('{')
            || trimmed == "}"
        {
            continue;
        }

        // Match `key: value;` — the colon separates key from value,
        // the trailing semicolon terminates the binding.
        if let Some(colon_in_trimmed) = trimmed.find(':') {
            if let Some(semi_in_trimmed) = trimmed.rfind(';') {
                if semi_in_trimmed > colon_in_trimmed {
                    let key = trimmed[..colon_in_trimmed].trim();
                    // Locate the value within the full source line.
                    let leading_ws = line.len() - line.trim_start().len();
                    let colon_abs = line_start + leading_ws + colon_in_trimmed;
                    // Value starts after ": " (colon + space).
                    let value_start = colon_abs + 1;
                    let value_start = value_start
                        + source[value_start..clamped_end]
                            .bytes()
                            .take_while(|b| *b == b' ')
                            .count();
                    let semi_abs = line_start + leading_ws + semi_in_trimmed;
                    if value_start < semi_abs && semi_abs <= clamped_end {
                        props.push(PropSpan {
                            key: key.to_string(),
                            value_start,
                            value_end: semi_abs,
                        });
                    }
                }
            }
        }
    }
    props
}

pub fn line_byte_offsets(source: &str) -> Vec<(usize, &str)> {
    let mut result = Vec::new();
    let mut offset = 0;
    for line in source.split('\n') {
        result.push((offset, line));
        offset += line.len() + 1; // +1 for the '\n'
    }
    result
}

/// Render a document to an embeddable `.slint` preview component.
///
/// Unlike [`render_document_slint_source`] which emits
/// `BuilderRoot inherits Window`, this emits
/// `BuilderPreview inherits Rectangle` — suitable for embedding
/// inside a [`ComponentContainer`] via [`compile_slint_preview`].
pub fn render_document_slint_preview(
    doc: &BuilderDocument,
    registry: &ComponentRegistry,
    tokens: &DesignTokens,
) -> Result<String, RenderError> {
    render_document_slint_preview_with_assets(
        doc,
        registry,
        tokens,
        std::collections::HashMap::new(),
    )
}

/// Like [`render_document_slint_preview`] but accepts pre-resolved
/// asset paths so VFS-backed images can emit `@image-url()` references.
pub fn render_document_slint_preview_with_assets(
    doc: &BuilderDocument,
    registry: &ComponentRegistry,
    tokens: &DesignTokens,
    asset_paths: std::collections::HashMap<String, std::path::PathBuf>,
) -> Result<String, RenderError> {
    render_document_slint_preview_with_assets_and_data(
        doc,
        registry,
        tokens,
        asset_paths,
        std::collections::HashMap::new(),
    )
}

/// Like [`render_document_slint_preview_with_assets`] but also accepts
/// pre-resolved widget data. Nodes whose ID appears in `widget_data`
/// get the resolved data merged into their props before template
/// rendering — the unified pipeline for `WidgetContribution.data_query`.
pub fn render_document_slint_preview_with_assets_and_data(
    doc: &BuilderDocument,
    registry: &ComponentRegistry,
    tokens: &DesignTokens,
    asset_paths: std::collections::HashMap<String, std::path::PathBuf>,
    widget_data: std::collections::HashMap<String, serde_json::Value>,
) -> Result<String, RenderError> {
    let mut ctx = RenderSlintContext::new(
        tokens,
        registry,
        &doc.resources,
        &doc.prefabs,
        &doc.facets,
        &doc.facet_schemas,
        false,
    );
    ctx.asset_paths = asset_paths;
    ctx.widget_data = widget_data;
    let mut out = SlintEmitter::new();
    out.line("// Auto-generated preview by prism_builder.");
    out.blank();

    let has_grid = doc.page_layout.has_grid();

    out.block(
        "export component BuilderPreview inherits Rectangle",
        |out| {
            out.prop_color(
                "background",
                rgba_to_slint_literal(tokens.colors.background),
            );
            out.blank();
            if let Some(root) = &doc.root {
                if has_grid {
                    let margins = &doc.page_layout.margins;

                    let child_by_id: std::collections::HashMap<&str, usize> = root
                        .children
                        .iter()
                        .enumerate()
                        .map(|(i, c)| (c.id.as_str(), i))
                        .collect();

                    out.block("VerticalLayout", |out| {
                        out.prop_px("padding-left", margins.left as f64);
                        out.prop_px("padding-top", margins.top as f64);
                        out.prop_px("padding-right", margins.right as f64);
                        out.prop_px("padding-bottom", margins.bottom as f64);
                        emit_grid_cell(
                            doc.page_layout.grid.as_ref().unwrap(),
                            &child_by_id,
                            &root.children,
                            &mut ctx,
                            out,
                            1.0,
                        )
                    })
                } else {
                    out.block("VerticalLayout", |out| {
                        out.prop_px("padding", tokens.spacing.lg as f64);
                        out.prop_px("spacing", tokens.spacing.md as f64);
                        out.line("alignment: start;");
                        ctx.render_child(root, out)
                    })
                }
            } else {
                out.block("Text", |out| {
                    out.prop_string("text", "(empty document)");
                    out.prop_color("color", rgba_to_slint_literal(tokens.colors.text_secondary));
                    Ok(())
                })
            }
        },
    )?;
    Ok(out.build())
}

fn emit_grid_cell(
    cell: &GridCell,
    child_by_id: &std::collections::HashMap<&str, usize>,
    children: &[crate::document::Node],
    ctx: &mut RenderSlintContext<'_>,
    out: &mut SlintEmitter,
    stretch: f32,
) -> Result<(), RenderError> {
    let stretch_str = format!("{stretch:.6}")
        .trim_end_matches('0')
        .trim_end_matches('.')
        .to_string();
    match cell {
        GridCell::Leaf { node_id } => {
            if let Some(id) = node_id {
                if let Some(&idx) = child_by_id.get(id.as_str()) {
                    let child = &children[idx];
                    out.block("Rectangle", |out| {
                        out.line(format!("horizontal-stretch: {stretch_str};"));
                        out.line(format!("vertical-stretch: {stretch_str};"));
                        if RenderSlintContext::child_emits_position(child) {
                            ctx.render_child(child, out)
                        } else {
                            out.line("preferred-width: 0px;");
                            out.line("preferred-height: 0px;");
                            out.line("clip: true;");
                            out.block("VerticalLayout", |out| ctx.render_child(child, out))
                        }
                    })
                } else {
                    out.block("Rectangle", |out| {
                        out.line(format!("horizontal-stretch: {stretch_str};"));
                        out.line(format!("vertical-stretch: {stretch_str};"));
                        Ok(())
                    })
                }
            } else {
                out.block("Rectangle", |out| {
                    out.line(format!("horizontal-stretch: {stretch_str};"));
                    out.line(format!("vertical-stretch: {stretch_str};"));
                    Ok(())
                })
            }
        }
        GridCell::Split {
            direction,
            gap,
            tracks,
            children: cells,
        } => {
            let layout = match direction {
                SplitDirection::Horizontal => "HorizontalLayout",
                SplitDirection::Vertical => "VerticalLayout",
            };
            out.block(layout, |out| {
                out.line(format!("horizontal-stretch: {stretch_str};"));
                out.line(format!("vertical-stretch: {stretch_str};"));
                if *gap > 0.0 {
                    out.prop_px("spacing", *gap as f64);
                }
                for (i, cell) in cells.iter().enumerate() {
                    let child_stretch = match tracks.get(i) {
                        Some(crate::layout::TrackSize::Fr { value }) => *value,
                        _ => 1.0,
                    };
                    emit_grid_cell(cell, child_by_id, children, ctx, out, child_stretch)?;
                }
                Ok(())
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use serde_json::{json, Value};

    use super::*;
    use crate::component::{Component, ComponentId, RenderSlintContext};
    use crate::document::Node;
    use crate::layout::LayoutMode;
    use crate::registry::FieldSpec;

    // ── Slint-side test components ────────────────────────────────

    struct SlintHeading {
        id: ComponentId,
    }

    impl Component for SlintHeading {
        fn id(&self) -> &ComponentId {
            &self.id
        }
        fn schema(&self) -> Vec<FieldSpec> {
            vec![FieldSpec::text("text", "Text")]
        }
        fn render_slint(
            &self,
            _ctx: &RenderSlintContext<'_>,
            props: &Value,
            _children: &[Node],
            out: &mut SlintEmitter,
        ) -> Result<(), RenderError> {
            let text = props.get("text").and_then(|v| v.as_str()).unwrap_or("");
            out.block("Text", |out| {
                out.prop_string("text", text);
                out.prop_px("font-size", 24.0);
                Ok(())
            })
        }
    }

    struct SlintSection {
        id: ComponentId,
    }

    impl Component for SlintSection {
        fn id(&self) -> &ComponentId {
            &self.id
        }
        fn schema(&self) -> Vec<FieldSpec> {
            vec![]
        }
        fn render_slint(
            &self,
            ctx: &RenderSlintContext<'_>,
            _props: &Value,
            children: &[Node],
            out: &mut SlintEmitter,
        ) -> Result<(), RenderError> {
            out.block("VerticalLayout", |out| {
                out.prop_px("spacing", 12.0);
                ctx.render_children(children, out)
            })
        }
    }

    fn slint_registry() -> ComponentRegistry {
        let mut reg = ComponentRegistry::new();
        reg.register(Arc::new(SlintHeading {
            id: "heading".into(),
        }))
        .unwrap();
        reg.register(Arc::new(SlintSection {
            id: "section".into(),
        }))
        .unwrap();
        reg
    }

    // ── Slint walker tests ────────────────────────────────────────

    #[test]
    fn slint_source_wraps_body_in_builder_root() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "Hi" }),
                children: vec![],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains("export component BuilderRoot inherits Window"));
        assert!(source.contains("preferred-width: 1280px;"));
        assert!(source.contains("Text {"));
        assert!(source.contains(r#"text: "Hi";"#));
    }

    #[test]
    fn slint_source_renders_section_children() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![
                    Node {
                        id: "n2".into(),
                        component: "heading".into(),
                        props: json!({ "text": "A" }),
                        children: vec![],
                        ..Default::default()
                    },
                    Node {
                        id: "n3".into(),
                        component: "heading".into(),
                        props: json!({ "text": "B" }),
                        children: vec![],
                        ..Default::default()
                    },
                ],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains("VerticalLayout {"));
        assert_eq!(source.matches(r#"text: "A";"#).count(), 1);
        assert_eq!(source.matches(r#"text: "B";"#).count(), 1);
    }

    #[test]
    fn slint_source_empty_document_emits_placeholder() {
        let doc = BuilderDocument::default();
        let reg = ComponentRegistry::new();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains(r#"text: "(empty document)";"#));
    }

    #[test]
    fn slint_source_escapes_dsl_hostile_text() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "\"oops\"\nsecond" }),
                children: vec![],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains(r#"text: "\"oops\"\nsecond";"#));
    }

    #[test]
    fn slint_source_unknown_component_errors() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "missing".into(),
                props: json!({}),
                children: vec![],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let err = render_document_slint_source(&doc, &reg, &tokens).unwrap_err();
        assert!(matches!(err, RenderError::UnknownComponent(ref id) if id == "missing"));
    }

    // ── Mapped source tests (ADR-006) ────────────────────────────

    #[test]
    fn mapped_source_contains_markers() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "Hi" }),
                children: vec![],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let (source, map) = render_document_slint_source_mapped(&doc, &reg, &tokens).unwrap();
        assert!(source.contains("// @node-start:n1:heading"));
        assert!(source.contains("// @node-end:n1"));

        let span = map.span_for_node("n1").unwrap();
        assert_eq!(span.component, "heading");
        assert!(span.start < span.end);
        assert!(span.end <= source.len());
    }

    #[test]
    fn mapped_source_nested_nodes() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "s1".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![
                    Node {
                        id: "h1".into(),
                        component: "heading".into(),
                        props: json!({ "text": "A" }),
                        children: vec![],
                        ..Default::default()
                    },
                    Node {
                        id: "h2".into(),
                        component: "heading".into(),
                        props: json!({ "text": "B" }),
                        children: vec![],
                        ..Default::default()
                    },
                ],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let (source, map) = render_document_slint_source_mapped(&doc, &reg, &tokens).unwrap();

        assert!(map.span_for_node("s1").is_some());
        assert!(map.span_for_node("h1").is_some());
        assert!(map.span_for_node("h2").is_some());

        let s1_span = map.span_for_node("s1").unwrap();
        let h1_span = map.span_for_node("h1").unwrap();
        // Children should be nested within parent span.
        assert!(h1_span.start >= s1_span.start);
        assert!(h1_span.end <= s1_span.end);

        // Source should contain all markers.
        assert!(source.contains("// @node-start:s1:section"));
        assert!(source.contains("// @node-start:h1:heading"));
        assert!(source.contains("// @node-start:h2:heading"));
    }

    #[test]
    fn mapped_source_node_at_offset() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "root".into(),
                component: "heading".into(),
                props: json!({ "text": "Test" }),
                children: vec![],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let (_, map) = render_document_slint_source_mapped(&doc, &reg, &tokens).unwrap();

        let span = map.span_for_node("root").unwrap();
        let mid = (span.start + span.end) / 2;
        assert_eq!(map.node_at_offset(mid), Some("root"));
    }

    // ── PropSpan extraction tests ────────────────────────────────

    #[test]
    fn prop_spans_extracted_for_leaf_node() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "Hello" }),
                children: vec![],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let (source, map) = render_document_slint_source_mapped(&doc, &reg, &tokens).unwrap();

        let span = map.span_for_node("n1").unwrap();
        assert!(!span.props.is_empty(), "should have prop spans");

        let text_prop = span.props.iter().find(|p| p.key == "text");
        assert!(text_prop.is_some(), "should have 'text' prop span");
        let tp = text_prop.unwrap();
        let value_slice = &source[tp.value_start..tp.value_end];
        assert_eq!(value_slice, r#""Hello""#);
    }

    #[test]
    fn prop_spans_skip_child_properties() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "s1".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![Node {
                    id: "h1".into(),
                    component: "heading".into(),
                    props: json!({ "text": "Child" }),
                    children: vec![],
                    ..Default::default()
                }],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let (source, map) = render_document_slint_source_mapped(&doc, &reg, &tokens).unwrap();

        let s1_span = map.span_for_node("s1").unwrap();
        let s1_text_prop = s1_span.props.iter().find(|p| p.key == "text");
        assert!(
            s1_text_prop.is_none(),
            "section should not capture child's 'text' prop; got props: {:?}",
            s1_span.props
        );

        let h1_span = map.span_for_node("h1").unwrap();
        let h1_text_prop = h1_span.props.iter().find(|p| p.key == "text");
        assert!(h1_text_prop.is_some(), "child should have 'text' prop");
        let tp = h1_text_prop.unwrap();
        assert_eq!(&source[tp.value_start..tp.value_end], r#""Child""#);
    }

    #[test]
    fn prop_span_value_replacement_works() {
        let doc = BuilderDocument {
            root: Some(Node {
                id: "n1".into(),
                component: "heading".into(),
                props: json!({ "text": "Before" }),
                children: vec![],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let (source, map) = render_document_slint_source_mapped(&doc, &reg, &tokens).unwrap();

        let span = map.span_for_node("n1").unwrap();
        let tp = span.props.iter().find(|p| p.key == "text").unwrap();

        let mut new_source = String::new();
        new_source.push_str(&source[..tp.value_start]);
        new_source.push_str(r#""After""#);
        new_source.push_str(&source[tp.value_end..]);

        assert!(new_source.contains(r#"text: "After";"#));
        assert!(!new_source.contains("Before"));
    }

    // ── Layout mode DSL emission tests ───────────────────────────

    #[test]
    fn slint_source_absolute_node_emits_xy() {
        use crate::layout::AbsoluteProps;
        use prism_core::foundation::spatial::Transform2D;

        let doc = BuilderDocument {
            root: Some(Node {
                id: "root".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![Node {
                    id: "abs".into(),
                    component: "heading".into(),
                    props: json!({ "text": "Hi" }),
                    layout_mode: LayoutMode::Absolute(AbsoluteProps::default()),
                    transform: Transform2D {
                        position: [50.0, 100.0],
                        ..Default::default()
                    },
                    ..Default::default()
                }],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains("x: 50px;"), "source:\n{source}");
        assert!(source.contains("y: 100px;"), "source:\n{source}");
    }

    #[test]
    fn slint_source_absolute_node_emits_width_height() {
        use crate::layout::{AbsoluteProps, Dimension};
        use prism_core::foundation::spatial::Transform2D;

        let doc = BuilderDocument {
            root: Some(Node {
                id: "root".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![Node {
                    id: "abs".into(),
                    component: "heading".into(),
                    props: json!({ "text": "Hi" }),
                    layout_mode: LayoutMode::Absolute(AbsoluteProps {
                        width: Dimension::Px { value: 200.0 },
                        height: Dimension::Px { value: 80.0 },
                        ..Default::default()
                    }),
                    transform: Transform2D {
                        position: [10.0, 20.0],
                        ..Default::default()
                    },
                    ..Default::default()
                }],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains("width: 200px;"), "source:\n{source}");
        assert!(source.contains("height: 80px;"), "source:\n{source}");
    }

    #[test]
    fn slint_source_free_node_emits_xy() {
        use prism_core::foundation::spatial::Transform2D;

        let doc = BuilderDocument {
            root: Some(Node {
                id: "root".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![Node {
                    id: "free".into(),
                    component: "heading".into(),
                    props: json!({ "text": "Floating" }),
                    layout_mode: LayoutMode::Free,
                    transform: Transform2D {
                        position: [75.0, 30.0],
                        ..Default::default()
                    },
                    ..Default::default()
                }],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains("x: 75px;"), "source:\n{source}");
        assert!(source.contains("y: 30px;"), "source:\n{source}");
    }

    #[test]
    fn slint_source_relative_node_emits_offset() {
        use crate::layout::FlowProps;
        use prism_core::foundation::spatial::Transform2D;

        let doc = BuilderDocument {
            root: Some(Node {
                id: "root".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![Node {
                    id: "rel".into(),
                    component: "heading".into(),
                    props: json!({ "text": "Offset" }),
                    layout_mode: LayoutMode::Relative(FlowProps::default()),
                    transform: Transform2D {
                        position: [15.0, -10.0],
                        ..Default::default()
                    },
                    ..Default::default()
                }],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(source.contains("x: 15px;"), "source:\n{source}");
        assert!(source.contains("y: -10px;"), "source:\n{source}");
    }

    #[test]
    fn slint_source_relative_zero_offset_no_xy() {
        use crate::layout::FlowProps;

        let doc = BuilderDocument {
            root: Some(Node {
                id: "root".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![Node {
                    id: "rel".into(),
                    component: "heading".into(),
                    props: json!({ "text": "NoOffset" }),
                    layout_mode: LayoutMode::Relative(FlowProps::default()),
                    ..Default::default()
                }],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(!source.contains("x:"), "no x expected:\n{source}");
        assert!(!source.contains("y:"), "no y expected:\n{source}");
    }

    #[test]
    fn slint_source_absolute_wrapper_is_rectangle() {
        use crate::layout::AbsoluteProps;
        use prism_core::foundation::spatial::Transform2D;

        let doc = BuilderDocument {
            root: Some(Node {
                id: "root".into(),
                component: "section".into(),
                props: json!({}),
                children: vec![Node {
                    id: "abs".into(),
                    component: "heading".into(),
                    props: json!({ "text": "X" }),
                    layout_mode: LayoutMode::Absolute(AbsoluteProps::default()),
                    transform: Transform2D {
                        position: [10.0, 10.0],
                        ..Default::default()
                    },
                    ..Default::default()
                }],
                ..Default::default()
            }),
            ..Default::default()
        };
        let reg = slint_registry();
        let tokens = DesignTokens::default();
        let source = render_document_slint_source(&doc, &reg, &tokens).unwrap();
        assert!(
            source.contains("Rectangle {"),
            "Absolute wrapper should be Rectangle:\n{source}"
        );
    }

    // ── Full starter-registry compile tests ──────────────────────
}
