import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `src/loom-wasm/` is wasm-pack output regenerated by
  // `pnpm wasm:build` — it ships with its own `eslint-disable` banner
  // and `tslint:disable` directives. Lint it elsewhere (Rust source).
  globalIgnores(['dist', 'src/loom-wasm']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // Allow the conventional `_`-prefix to mark a destructured / function
      // argument we know is unused — primarily for the
      // `const { [path]: _gone, ...rest } = obj` pattern that drops a
      // property by rest-spread.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
])
