export {
  createIdentity,
  resolveIdentity,
  signPayload,
  verifySignature,
  exportIdentity,
  importIdentity,
  createMultiSigConfig,
  createPartialSignature,
  assembleMultiSignature,
  verifyMultiSignature,
  encodeBase58,
  decodeBase58,
  publicKeyToDidKey,
  didKeyToPublicKey,
  base64urlEncode,
} from "./identity.js";

export type {
  DIDMethod,
  DID,
  Ed25519KeyPair,
  KeyHandle,
  VerificationMethod,
  DIDDocument,
  PrismIdentity,
  ResolvedIdentity,
  PartialSignature,
  MultiSignature,
  MultiSigConfig,
  CreateIdentityOptions,
  ResolveIdentityOptions,
  ExportedIdentity,
  ImportIdentityOptions,
} from "./identity-types.js";
