//! Hand-maintained Luau type stubs for the runtime's value types.
//!
//! Walked by `prism codegen luau-types` to produce
//! `<workspace>/types/prism-ui.d.luau` — the per-component stub file
//! Luau handlers consume so authoring `ui.container({...})` (see
//! [`crate::luau`]) gives strongly-typed completions and hover.
//!
//! Same shape as `prism_core::luau_types::type_defs()`: a hand-rolled
//! `Vec<(name, def)>` rather than `inventory!`-style link-time
//! collection, because the daemon's cdylib + WASM targets don't
//! reliably surface distributed slices. Add an entry here whenever a
//! new value type lands in [`crate::layout`] or [`crate::command`].
//!
//! The constants below are deliberately plain strings rather than
//! `#[luau_expose]`-derived associated items: keeping them out of the
//! derive macro lets the runtime stay `mlua`-feature-free for the
//! relay / SSR build, while the type stubs themselves are still
//! always available.

/// `export type` strings, one per runtime value type. Curated leaf-
/// first so referenced types declare before their dependents.
pub fn type_defs() -> Vec<(&'static str, &'static str)> {
    vec![
        ("Color", COLOR),
        ("CornerRadius", CORNER_RADIUS),
        ("Padding", PADDING),
        ("Sizing", SIZING),
        ("Direction", DIRECTION),
        ("Viewport", VIEWPORT),
        ("TextProps", TEXT_PROPS),
        ("ContainerProps", CONTAINER_PROPS),
        ("Node", NODE),
        ("Rect", RECT),
        ("RenderCommand", RENDER_COMMAND),
    ]
}

/// Concatenate every entry from [`type_defs`] into a single Luau
/// source file, prefixed with `--!strict`. Mirrors
/// `prism_core::luau_types::render_type_stubs`.
pub fn render_type_stubs() -> String {
    let mut out = String::from(
        "--!strict\n-- Generated by `prism codegen luau-types`. Do not edit by hand.\n\n",
    );
    for (_, def) in type_defs() {
        out.push_str(def);
        out.push_str("\n\n");
    }
    out
}

const COLOR: &str = "export type Color = {
    r: number,
    g: number,
    b: number,
    a: number,
}";

const CORNER_RADIUS: &str = "export type CornerRadius = {
    tl: number,
    tr: number,
    br: number,
    bl: number,
}";

const PADDING: &str = "export type Padding = {
    left: number,
    right: number,
    top: number,
    bottom: number,
}";

// Sizing is a tagged union mirroring the serde representation
// (`#[serde(tag = "mode", content = "value")]`). Luau side accepts
// `{ mode = "fit" }`, `{ mode = "grow" }`, `{ mode = "fixed", value = 40 }`.
const SIZING: &str = "export type Sizing =
    { mode: \"fit\" }
    | { mode: \"grow\" }
    | { mode: \"fixed\", value: number }";

const DIRECTION: &str = "export type Direction = \"row\" | \"column\"";

const VIEWPORT: &str = "export type Viewport = {
    width: number,
    height: number,
}";

const TEXT_PROPS: &str = "export type TextProps = {
    font_size: number,
    color: Color,
}";

const CONTAINER_PROPS: &str = "export type ContainerProps = {
    direction: Direction,
    gap: number,
    padding: Padding,
    width: Sizing,
    height: Sizing,
    background: Color?,
    radius: CornerRadius,
}";

// `Node` mirrors the `#[serde(tag = "kind")]` representation in
// `layout::Node` — the same shape `mlua::LuaSerdeExt` uses to round-
// trip through Lua tables.
const NODE: &str = "export type Node =
    { kind: \"container\", id: string, props: ContainerProps, children: { Node } }
    | { kind: \"text\", id: string, content: string, props: TextProps }
    | { kind: \"spacer\", id: string, width: number, height: number }";

const RECT: &str = "export type Rect = {
    x: number,
    y: number,
    width: number,
    height: number,
}";

// Backend-neutral render command. Tagged union mirroring the Rust
// enum's serde representation.
const RENDER_COMMAND: &str = "export type RenderCommand =
    { Rectangle: { bounds: Rect, color: Color, radius: CornerRadius } }
    | { Border: { bounds: Rect, color: Color, width: number, radius: CornerRadius } }
    | { Text: { bounds: Rect, content: string, color: Color, font_size: number } }
    | { Image: { bounds: Rect, source: string } }
    | { ScissorStart: { bounds: Rect } }
    | \"ScissorEnd\"
    | { Hint: { key: string, value: string } }";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_includes_every_value_type() {
        let names: Vec<&str> = type_defs().iter().map(|(n, _)| *n).collect();
        for expected in [
            "Color",
            "CornerRadius",
            "Padding",
            "Sizing",
            "Direction",
            "Viewport",
            "TextProps",
            "ContainerProps",
            "Node",
            "Rect",
            "RenderCommand",
        ] {
            assert!(
                names.contains(&expected),
                "missing {expected} from prism-ui-runtime luau type registry"
            );
        }
    }

    #[test]
    fn node_def_is_tagged_union_with_three_variants() {
        let def = NODE;
        assert!(def.contains("kind: \"container\""));
        assert!(def.contains("kind: \"text\""));
        assert!(def.contains("kind: \"spacer\""));
    }

    #[test]
    fn render_type_stubs_emits_strict_header_and_every_def() {
        let rendered = render_type_stubs();
        assert!(rendered.starts_with("--!strict\n"));
        for (_, def) in type_defs() {
            assert!(rendered.contains(def), "stub missing: {def}");
        }
    }
}
